### ISSUE TITLE
Unhandled promise rejections

### ISSUE THREAD

**Issue by matthiasfeist** [OptimalBits/bull#1012]
## Description
We're updating from Bull 3.3.8 to the latest version and all the sudden we see the an unhandled Promise rejection happening when we're trying to start Bull when Redis is not yet ready and the connection fails. This is happening with every version after 3.3.8

## Minimal, Working Test code to reproduce the issue.
```
const Queue = require('bull')
const Redis = require('ioredis')

const redis = new Redis({
  port: 6379,
  host: '127.0.0.1',
  showFriendlyErrorStack: true,
  password: 'foobared',
})

redis.on('connect', () => console.log('Redis connected'))
redis.on('reconnecting', delay => console.log('reconnecting: ' + delay))
redis.on('error', error => console.log('error'))

const videoQueue = new Queue('video transcoding', redis)
```

## Bull version
every version after 3.3.8

### Notes:
I did a brief investigation since the major thing that is different from 3.3.8 to 3.3.9 is the isRedisReady function. So I went in and added `return Promise.resolve()` as a first line into this function and that made Bull behave as before (trying to reconnect). When I added `return Promise.reject()` as a first line in this function, my node env crashed with a unhandled Promise rejection. So I assume the bug is somewhat related to this function and it's usage somewhere...

**Comment by manast** [comment]
It is not completely easy to define which should be the correct behaviour, but I am leaning more to the current one, where the user needs to handle the connection errors manually instead of relaying on a automatic reconnection logic that sometimes works an sometimes it doesn't. By putting the responsibility on the user we can provide a more consistent behaviour.

**Comment by matthiasfeist** [comment]
That is also ok with me. But if the user 8s supposed to handle this, then I'm not sure how to do this. Do you have a code example for me?

**Comment by matthiasfeist** [comment]
However no matter how's responsibility it is, there is still the issue of an unhandled promise rejection somewhere...

**Comment by matthiasfeist** [comment]
I investigated a bit further and found the following. It looks like that ioredis connects automatically once `new Redis` is called. And if the Redis server is not up, that means it's gonna throw an Error which then results in the unhandled promise rejection.

When I modify my test code like this, I don't get the unhandled rejection anymore:
```javascript 
const Queue = require('bull')
const Redis = require('ioredis')

async function test() {
  const redis = new Redis({
    port: 6379,
    host: '127.0.0.1',
    showFriendlyErrorStack: true,
    password: 'foobared',
    lazyConnect: true,
  })

  redis.on('connect', () => console.log('Redis connected'))
  redis.on('reconnecting', delay => console.log('reconnecting: ' + delay))
  redis.on('error', error => console.log('error', error))
  try {
    await redis.connect()

    const videoQueue = new Queue('video transcoding', redis)
  } catch (error) {
    console.log('catched error', error)
  }
}

test()
```

**Comment by delanni** [comment]
So here's an example you can test actually:
```
const Queue = require("bull");

process.on("unhandledRejection", (reason, p) => {
  console.log("Unhandled Rejection at:", p, "reason:", reason);
  // We quit because we don't want unhandled rejections, and later node versions will do too
  process.exit(1);
});

const videoQueue = new Queue("video transcoding", {
  redis: {
    port: 6666,
    host: "127.0.0.1",
    showFriendlyErrorStack: true,
    password: "foobared"
    // lazyConnect: true
  }
});

videoQueue.on("error", err => console.log(err));
```

You'll see that versions, even with patch version after 3.3.8 will be quitting the application due to unhandled promise rejection.

I understand it should be the user's responsibility, but how? Re-instantiating bull continuously? What was wrong with the previous retry behaviour? Also, shouldn't the retry behaviour be completely removed to make users handle this, instead of just letting an error bubble up?

**Comment by matthiasfeist** [comment]
@manast Do you have any more updates on this?

**Comment by manast** [comment]
sorry for the slow responses, I have been quite busy and this issue requires a bit of investigation time. 

Ok, so the change after 3.3.8 was due to the issue where you did not have a working connection and the queue did not emit any error at all, so the user kept wondering what was happening since no error was emitted but the queue did not work. The new mechanics is that you need at least to have a working connection during the initialisation of the queue, after that "ioredis" command offline cache will kick in and you will not get any further errors unless you pass the redis option ```enableOfflineQueue``` (https://github.com/luin/ioredis/blob/master/API.md), in that case error connection will be bubbled up from redis and you can take some kind of action.

Now, the current solution may not be ideal, but it is a trade-off between something that can be worked-around while keeping backwards API compatibility. So all that is required for this to work in your use case is that you need to be sure that you have a working connection at the initialization time of the Queue, you may be able to use the ```isReady``` method that resolves when the queue is ready (which you normally not need to use).

If you have any proposal that would make the current solution work better I am all ears... If the change is a breaking change we will need to bump the major version though.

**Comment by matthiasfeist** [comment]
@manast No problem for the late reply, it's summer after all and one should enjoy the sun :)

Again to reiterate: My problem is not that some sort of behaviour changed but that some error somewhere in Bull is not catched when I try to instantiate Bull with a offline Redis connection resulting in an _unhandled promise rejection_ warning. The error says `DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.` and that is exactly why I think that a **un-catched and un-handled** promise rejection in Bull is a bad thing and should be fixed.

I also am not exactly following what you are trying to say in your post before. Can you maybe post some code that shows how I should handle the redis connection and Bull so that I don't get a unhandled promise rejection whenever I try to instantiate Bull? Sorry, but I'm really lost at the moment 😅

**Comment by manast** [comment]
ok, I think I can fix that by catching the error and re-emitting it as an event instead.

**Comment by manast** [comment]
So, we are already emitting the error, but in order to avoid the warning we can just add a dummy catch on the ```_initializing``` promise. I can make a proper release but you can test already that adding this code ```js
_this._initializing.catch( err => {});
```
to this line: https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L155
will eliminate the warning.

**Comment by matthiasfeist** [comment]
Yes that does the trick! Very nice! Thank you!
I'll wait for the release :)

**Comment by matthiasfeist** [comment]
@manast Do you want me to push up a PR or are you fixing this in a new release?

**Comment by manast** [comment]
done!

**Comment by matthiasfeist** [comment]
Sweet! thank you!
So I assume this will be released with the next release then?
