### ISSUE TITLE
Get a list of all bull queues on redis

### ISSUE THREAD

**Issue by cesarvarela** [OptimalBits/bull#1024]
Is it possible? 

Thanks

**Comment by canyoudev** [comment]
I have the same question. Please help!
Guys, thanks for the package, but your Docs aren't begginer friendly.

**Comment by canyoudev** [comment]
@cesarvarela did you managed to solve this?

**Comment by aleccool213** [comment]
@canyoudev what things were not beginner friendly?

**Comment by manast** [comment]
Here some inspirational code to get the queues:
```js
var queueNameRegExp = new RegExp("(.*):(.*):id");
const keys = await redisClient.keys("*:*:id");
      queues = keys.map(function(key) {
        var match = queueNameRegExp.exec(key);
        if (match) {
          return {
            prefix: match[1],
            name: match[2]
          };
        }
      });
```

**Comment by cesarvarela** [comment]
I ended up not needing it.

btw, thanks for the example, you can close the issue if you want.

**Comment by canyoudev** [comment]
@manast @aleccool213 thanks for responses. 

After reading Docs more carefully and spending more time with this package I ended up with idea that you guys intentionally leave all this space for developer to solve. This is a good idea, since you doesn't pollute source code with API that devs could implement themselves. It's just me get used to all this huge API's.

The only thing is missing for me in Docs, is good practices and code examples, like this. But after all, since there's pretty intensive discussions in issues, I could find plenty of examples there, which is nice. So thanks!

**Comment by PaulGrimshaw** [comment]
I actually disagree, i think this should be within the library.  I think the way redis works to store and manage queues should be completely internal to bull.  Having external APIs depending on the internal redis structure is brittle, and also will restrict changes and enhancements in the future with bull.
