### ISSUE TITLE
job.update is not available in sandbox processor

### ISSUE THREAD

**Issue by MrNghia123** [OptimalBits/bull#1056]
I followed the README.md to create a sandbox processor
```js
// processor.js
module.exports = function(job){
  // Do some heavy work
  job.update(newJobData);         <= error here
  return Promise.resolve(result);
}
```

When I move back the processor to the same process, job.update works fine

**Comment by sz332** [comment]
Hello,

I am struggling to return even a simple result from a sandbox processor, do you have a working example? If so, can you please add it to the task and/or put it on github?

**Comment by manast** [comment]
@sz332 you should be able to listen to the completed event like this:
```
queue.on('global:completed', function(jobId, result) {
  console.log(`Job ${jobId} completed! Result: ${result}`);
});
```

**Comment by sz332** [comment]
https://gist.github.com/sz332/4412f130214ec2bb02078e88c2ee1462

Created a working gist :)

**Comment by sz332** [comment]
@manast  To @MrNghia123's question: is there a solution or a pattern available for the purpose to provide job status information? We can always make a direct connection to Redis from the processor, but it does not feel very elegant. Any advice?

**Comment by MrNghia123** [comment]
So @manast , is the sandboxed processor designed not to make connection to Redis so it cannot provide function like job.update inside it?

**Comment by MrNghia123** [comment]
@sz332 , I am not so sure if I understand your question. In my project there is some job information which I can only acquire "during" the job processing, and I need to save this information to be used later on, that's why I need to call job.update inside the processor to update the job with the new data.

**Comment by sz332** [comment]
@MrNghia123 my mistake, i have a different requirement, and just read the original comment. Short description about what i would like to do and then some comments about your problem..

What I would like to achieve is the ability to somehow get the status of a long running job. The reason is that I have very long running, CPU intensive jobs, which can run for 10 minutes or even more, and I would like to have an interface where the user can throw in (POST) a job to a queue, and call periodic get's about the status. The way nodejs works (using a single thread) is not very good for this purpose because a long running job will block the whole thread. So I had two solutions: one, is to rewrite the algorithm (which is a graph theory algorithm i don't really want to rework NOW) or execute the calculation in a separate thread. The way I understand what the sandbox processor provides is exactly that: it creates a new thread/process/whatever where the code can run and not block the nodejs event thread.

Your case is a little bit different, but I think you can simply start the long running job, get the new data, and return this data with return Promise.resolve(result). Then, you can use this result in the queue.on event listener to combine the old state, and the new one, and perhaps throw in a new job in the same (or another) thread.

**Comment by manast** [comment]
@MrNghia123 that ```job.update``` is not implemented in sandboxed processors, I will mark it as an update and implement it in the next version.

**Comment by manast** [comment]
@sz332 you can pass progress information using ```job.progress```, we have a issue requesting that instead of just passing a progress value we should also be able to pass a custom object.

**Comment by MrNghia123** [comment]
For now I managed to put all the newly generated information in to the result and do the updates in the queue completed event. 
I am not sure if the job.update inside the processor is still in need.
Thanks for your support.

**Comment by thbl** [comment]
+1

**Comment by betimer** [comment]
@manast How is this going? is it implemented in the latest version? Thank you
