### ISSUE TITLE
Returning data on job completion

### ISSUE THREAD

**Issue by TimNZ** [OptimalBits/bull#11]
What is the good reason why neither you or Kue support returning data in done()?

A pain in the ass needing to persist a response through another mechanism.

**Comment by LewisJEllis** [comment]
Any further thoughts on this? I see the potential workaround with a response queue for each frontend server, but it could be much simpler to have it built in.

**Comment by manast** [comment]
Yes, although it is feasible to return data in the onCompleted event when a job has been performed, I dont really think it is a good practice, simply because it is not guaranteed that you will be listening at the right time and you will end loosing data. Best is to use a different queue to transmit results from the worker to the process that needs the results, that way you will always get the end results and not loose any data.

**Comment by TylerBrock** [comment]
Hey did you ever wind up adding this feature? It would be killer to have bull support this use case.

**Comment by albertjan** [comment]
@TylerBrock see #178

**Comment by TylerBrock** [comment]
@albertjan thanks. Nice work sir!

**Comment by rinogo** [comment]
For those who land here from Google: [Bull 3.0.0. RC 4](https://github.com/OptimalBits/bull/blob/develop/CHANGELOG.md#v300-rc4) added support for the glorious [`await job.finished()`](https://github.com/OptimalBits/bull/blob/HEAD/REFERENCE.md#jobfinished). Enjoy! :)
