### ISSUE TITLE
pm2 cluster mode

### ISSUE THREAD

**Issue by rsaphala** [OptimalBits/bull#1195]
Are there any benefits running bull in separate processes along with pm2 cluster mode?

**Comment by manast** [comment]
not that I can think of...

**Comment by loris** [comment]
@manast What about worker threads (https://medium.com/lazy-engineering/node-worker-threads-b57a32d84845) now available Node v10.7 to handle threaded processors?

**Comment by manast** [comment]
worker threads are still experimental, but we already support sandboxes running in separate processes and cluster mode, please check the documentation.

**Comment by manast** [comment]
Node 11 is not an stable version, that would be version 12. When the worker_threads become stable we will see if they can fit and provide some value to the library.

**Comment by chaffeqa** [comment]
Any chance on attempting this? wouldnt mind helping, basically this is our bottleneck now, we never get above 40% cpu on our worker containers because we dont have ability to do `threaded processors` since we transpile everything down, however we have both very heavy CPU jobs, and jobs with mainly IO related work.  I'm thinking of looking into node cluster to try to get more out of the container resources, but I'd much prefer something like `threaded processors` but using `worker_threads` instead

**Comment by manast** [comment]
@chaffeqa have you tried using sandboxed workers?

**Comment by chaffeqa** [comment]
No since when transpiling, we just build a single script `worker.js` and not one per job type (we have ~20).  Is there a something I'm missing or would I have to create a script file for each job?

**Comment by manast** [comment]
as long as the worker is specified as an external file it will be run in its own process, maybe you need to increase concurrency to use more processes in parallel.

**Comment by chaffeqa** [comment]
Just for a bit of code communication, we have something like:

```ts
// run-worker.ts
import Manager from "../worker";

Manager.work().catch((err) => {
  console.error(`worker error:`);
  console.error(err);
  process.exit(1);
});
```
```ts
// worker.ts
class Manager {
  public jobs = {
    TestJob,
    // ...
  };

  public processJob = async (bullJob: BullJob) => {
    const {jobName, payload} = bullJob.data;
    const jobKlass = this.jobs[jobName];
    const jobInstance = new jobKlass(payload);
    const result = await jobInstance.perform(bullJob);
    return result
  }

  public async work() {
    const queue = this.getQueue("all");
    queue.process("*", this.processJob);
    // ...
  }
  
}
export default new Manager()
```

So maybe having something like:

```ts
// process-job.ts
import Manager from "../worker";
async function processJob(job: BullJob){
  const manager = new Manager()
  return manager.processJob(job)
}
export default processJob
```

And transpile that file as an entrypoint?

**Comment by manast** [comment]
check this: https://github.com/optimalbits/bull#separate-processes

**Comment by chaffeqa** [comment]
Right thats what i was refering to above, however we have our `Job` set up as a class with a `perform` function.  So we can't really follow the exact approach in that documentation.  The above example I gave was an attempt to adopt that approach DSL, but that is why I'd prefer something like `worker_threads` since it wouldnt require adhering to that DSL (we try to stick with es7 `import`s and  not `require`)

**Comment by manast** [comment]
thing is, if you define the processor like this: ```queue.process("*", this.processJob);``` it will run all the workers the same process, whereas this ```queue.process("*", "myfileprocessor.js");``` will run them in separate processes and therefore will exploit multiple CPUs if available.

**Comment by chaffeqa** [comment]
Yea thats what I was trying to achieve with introducint `process-job.ts` and using that as the `"myfileprocessor.js"`... my point is: we can move to support that (after thinking about how we would change our implementation), however I still would prefer a `worker_threads` approach in our use case.

Do you think it would be hard to work into the library?

**Comment by tschmidt64-SC** [comment]
is there any way to get sandboxed processes programmatically rather than the sort of scripting lang style as currently implemented? We use typescript and it would be nice if we could get type checking rather than basically just having bull run the javascript file as a script in a separate process. It's not a huge deal but the current 'pass the file name' interface seems a little hacky
