### ISSUE TITLE
Processes are created for queues, but not removed

### ISSUE THREAD

**Issue by aplumb-neurala** [OptimalBits/bull#1202]
So I've seen that there are several similar issue reports, but I'm not sure what the state of those are or if they are actually related to what I'm experiencing.

My use case is that I have about a dozen or so queues that spawn new processes, most have a concurrency of 1.  What I'm finding is that bull will launch the processes for these jobs but then they never get shut down, and the node process remains running, so the memory is never released.  The memory consumption chart for these servers is a quick rise up to some plateau that is never reduced.

My ideal would be a situation where I could indicate a maximum number of allowed child processes per server.  If I could do that, then I wouldn't be worrying so much about the memory usage.  Is this possible?

Alternatively it would also be good for unused processes to be shutdown.  I would be ok with shutting down the process after every job since I'm not doing anything that requires especially short latency.  Barring that, if I have a process that has gone unused for some amount of time (let's say 30m) then that can be shut down.

I couldn't find solutions to either of these problems in the docs, so please let me know if I missed anything.
Thanks!

**Comment by manast** [comment]
I would love to have a test case that reproduces this issue. I have tried many times and I cannot reproduce it myself...

**Comment by DavideViolante** [comment]
Related to my issue too https://github.com/OptimalBits/bull/issues/1194
@manast to find it I would check all the changes between v3.4.8 (working fine) and v3.5.3 (I think v3.5.0 is the one that is introducing the problem, but not sure). I'm just sure that there is a problem between these 2 versions (didn't test v3.6.0 yet).

**Comment by jmif** [comment]
We ran into this as well just recently on 3.10.  Reading through the process child code it looks like sub processes used to execute jobs are only cleaned up when the queue itself is cleaned up.  Because child processes are never killed we can get into a situation where a significant number of idle processes are consuming memory.  I haven't been able to identify specific steps to repro but an initial read of the code indicates that if there are no child processes available the child pool will always create another one, so if a queue tries to execute more jobs than it has child process workers it will create another one.  With enough spikes in concurrent job executions this could result in a lot of unnecessary processes.

However, if we clean up free workers in the child pool we do not run out of memory.  We now run this code block on an interval in our queue runners:

```
for (const queue of queues) {
  if (queue.childPool) {
    for (const freeChild of queue.childPool.getAllFree()) {
      queue.childPool.kill(freeChild, 'SIGTERM')
    }
  }
}
```

**Comment by jmif** [comment]
@manast makes sense, I haven't been able to find a code path that could be a likely cause but I can definitely say deploying that cleanup code (no other changes went out with it) has completely resolved our memory issues.  We're also using rate limiting on many of our queues and we set a concurrency limit (usually between 1 to 3).  We're also running about 30 different queues from the same master process.

Thinking out loud here: could be a race condition in the job start / child pool selection code path or potentially in the child pool free code path that causes a child worker to not be marked as free before the job asks the child pool for a free worker? 

I do think it's worth getting to the bottom of this but in addition I think it'd be useful to add some kind of configurable timeout on stale processes (after being freed and idle for some amount of time the process is released).  It's not a solution to the problem we're seeing but there's no need to keep around the process memory, potentially open database connections, etc.

**Comment by DavideViolante** [comment]
@manast I would recommend you to [check again the changes between these 2 versions](https://github.com/OptimalBits/bull/compare/v3.4.8...v3.5.2), because at the time I tested I was 100% sure that the memory leak is present in v3.5.2 and not present in v3.4.8.
Summarizing all the info from the people that reported the memory increases:
- it happens after v3.4.8
- it happens with many queues and many many jobs
- it may be related to Bluebird (there are bluebird changes in the 3.5.2, it might be really this!)
- related issues: https://github.com/OptimalBits/bull/issues/1110 https://github.com/OptimalBits/bull/issues/1194

**Comment by manast** [comment]
@DavideViolante I have rechecked the code many times and I really cannot find any change that would cause the issue. With a reproducible test case there would be a chance otherwise I do not really know what else to do.

**Comment by DavideViolante** [comment]
I'm not working in that company anymore, I really cannot reproduce it again.
Anyway I can provide some code portions that might give you some hints to reproduce it:
```
v3.5.2
```

```js
// Global config
const redisConfig = { host: 'localhost', port: 6379 };
const globalConfig = {
  redis: redisConfig,
  defaultJobOptions: {
    attempts: 2,
    timeout: 1000 * 60 * 60 * 24 * 3, // 3d
    backoff: 60 * 1000, // 60s
    priority: 1
  },
  // https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#reusing-redis-connections
  createClient: (type) => {
    switch (type) {
      case 'client':
        return client;
      case 'subscriber':
        return subscriber;
      default:
        return new Redis(redisConfig);
    }
  }

// Queue config
const queuesConfiguration = {
  limiter: {
    max: 1,
    duration: 5000
  }
}
new Queue('test', _.merge({}, globalConfig, queuesConfiguration).process('*', 20, `handleQueue.js`);;
// Note the code is not exactly like this but the config is.
```

Then create many many jobs (even 50k or more) in this queue. The jobs should get for some seconds to get completed. The jobs should be processed as 20 concurrently.
Then monitor the memory of the process that is running this queue for at least 30mins and the memory will never get down.
Then test again with 3.4.8 and the memory is stable.

**Comment by elliotaplant** [comment]
> @jmif but the queue will not require more child processes than the concurrency parameter, so there should never be more child processes than that.

We're having this issue too. Our problem is not that the number of child processors is higher than expected, it's that the processes never unload the memory they are taking (possibly because they never exit). Would you expect the processes to dump their memory on completion?

Thanks for the hard work you're doing @manast!

**Comment by manast** [comment]
@elliotaplant as long as there are no memory leaks, V8 should garbage collect all not used memory of the worker process as in any other process.

**Comment by elliotaplant** [comment]
That's great to know. I'll see if I can find the leak or make a small repo to reproduce e the issue. Do you have a set of tools you like to use so I can make the easy for you to run? If you don't have a preference, I'll use a docker-compose file to set up the app and redis.

**Comment by manast** [comment]
As long as it is super simple and only includes the absolute minimum to reproduce the issue I am ok with it.
