### ISSUE TITLE
Url parameter being ignored

### ISSUE THREAD

**Issue by mamasselin** [OptimalBits/bull#1338]
## Description

When I specify both `url` and `options` to a queue, it seems to cause the url to be ignored.

For example:

```
const Queue = require('bull')

const myQueue = new Queue('my-queue', 'redis://192.168.0.100:6464', { redis: { enableReadyCheck: false } })
```

When I look at `myQueue` afterward I can see that the host and port are actually set to `127.0.0.1` and `6379` and therefore fails to connect.

If I remove the `options`:

```
const Queue = require('bull')

const myQueue = new Queue('my-queue', 'redis://192.168.0.100:6464')
````

The host and port are now properly set to `192.168.0.100` and `6464` respectively and the connection is successful.

## Bull version

3.10.0

**Comment by stansv** [comment]
The possibility to pass a URL to Queue constructor is just made for convenience in case you agree with defaults. If you need to modify any connection option not related to URL, you should use `redis` option key instead of `url` argument. Though we can add a bit logic to merge redis options object with `url`. It should be pretty easy, I can prepare a PR if anyone interested.

For now you can write something like [redisOptsFromUrl](https://github.com/OptimalBits/bull/blob/develop/lib/queue.js#L290) function used inside bull to conveniently create `ioredis` options for your URL.

**Comment by mamasselin** [comment]
Thanks for the reply! I will use something like `redisOptsFromUrl` as it's more convenient for me to keep it as a url.
