### ISSUE TITLE
Processor setting notification

### ISSUE THREAD

**Issue by ks-s-a** [OptimalBits/bull#1368]
Hello.

What's the best way to get known that we attached a processor via .process method and waiting for tasks.

As I understood from #882 issue it is not correct just to put .then after .process method, but I would like to get a point of time when I successfully attached handler and ready to process new tasks.

**Comment by manast** [comment]
you do not have to wait, after defining the processor you can assume tasks can be processed by it.

**Comment by stansv** [comment]
@manast can `isReady()` help here? Is there a way to create queue in paused state, so that one can then resume it and handle appropriate event?

@ks-s-a depending on your specific case and needs, maybe it will be enough to just push a special no-op job to queue with highest priority (1) and once this job is taken you will know job handler is registered and ready. But could you please share more information on why do you have this need?

PS Do not try to get promise returned from process() method, looks like normally it never resolves while node process is running.

**Comment by ks-s-a** [comment]
@stansv I need it just to be sure that the processor function was set. We don't have a checker for the task processing and I'm afraid to get a case when the tasks are just collecting in queue and we can't see any error and notification message. Additionally I would like to log the moment when we set processor to make further debugging easier.

**Comment by stansv** [comment]
@ks-s-a you can never be sure your worker will always have good connection to Redis until it's running on same machine, hence job processor can stop working at any moment. To log connectivity errors attach listener to "error" event on a Queue instance.

I think what you need is a kind of backpressure mechanism to slow down pushing new jobs into a queue. Just check `queue.getWaitingCount()` is below some threshold before adding a job. Depending on your application, you also may want to throttle your process producing jobs. For example, if job is produced as a result of rest API call, just return error to client.
