### ISSUE TITLE
How to implement resumable stream for fault-tolerance to avoid data-loss?

### ISSUE THREAD

**Issue by zhenyulin** [OptimalBits/bull#1384]
#607  Description

I'm currently using bull-queue to implement the control over a data-processing-stream in Nodejs. The stream would load a large file from the storage system, enrich it, and then write it to a database. The workers are running on k8s for easy horizontal scaling. The problem I got is during scaling there has been some instance failure, which leads to job failure due to long stalling as worker instances shut down. When restarting the worker, I need to manually put the failed job to retry to join the queue, while the worker would restart the stream from the beginning.

It is possible to record how many bytes have been processed in a job, and reflect that in the job progress, however, failed jobs wouldn't carry the last progress data point so that it can be picked up to resume the stream from where it is stopped last time. As due to sudden worker instance shut down, it is not very possible to pause the stream programmatically.

Also in order to retry failed jobs programmatically, the failed jobs also need to carry error information and made it accessible to determine whether to retry the job or not.

## Key Feature Request
The key feature needed here is for `failed jobs` to carry `metadata` from `job progress` and `error`. I'm not sure if this has been implemented yet.

## Bull version
latest

**Comment by manast** [comment]
hmm, you should be able to get the progress data of a job independently if it has completed or failed, is this not working for you?

**Comment by zhenyulin** [comment]
@manast I found the data is in ._progress, but I've made a workaround to update the progress to job.data

**Comment by zhenyulin** [comment]
@manast can I get some more insights on how the `lockPeriod` and `stall` logic works in the scenario of worker instance crash?

say I've 10 pods of workers, processing heavy 10 jobs; 2 of them crash during the process due to un known reasons, and new pods being spawned in 1-2 mins; during the process the job in the active queue would be locked for the default 30s? after that time, new worker instance would be able to pick them up; otherwise after the stall period of default 30s, they would be moved to failed jobs due to being stalled for too long?

**Comment by stansv** [comment]
@zhenyulin as you already found you can indeed persist your checkpoints with `job.progress()`.

Increase `maxStalledCount` so that stalled jobs would have more times available to return back to queue.

When worker is lucky to take new job from queue, it pushes a special lock key into Redis with TTL of 30 seconds (default `lockDuration`). After that time key is automatically removed by Redis. While job is processed by your `process()` callback, Bull automatically increases TTL of lock key for you before it reaches zero (with rate defined by `lockRenewTime`, which is 15s by default). If node fail to increase lock for some reason, any other worker can found that the job is active but there's no lock, and either move job back to queue in waiting state or fail it, if `stalledCounter` have reached maximum value (1) — see https://github.com/OptimalBits/bull/blob/develop/lib/commands/moveStalledJobsToWait-7.lua for details. There's also `stalled-check` key with its own TTL (defined by `stalledInterval`) preventing nodes from running this procedure too often.

When stalled job is restarted you can always retrieve saved progress from job object as `job.progress`:

```
{
  "id": "1",
  "name": "__default__",
  "data": {
    "data": true
  },
  ...
  "progress": {
    "lastJournalNumber": 6377 
  },
  "delay": 0,
  "timestamp": 1563260780414,
  ...
}
```

**Comment by zhenyulin** [comment]
@stansv thanks for the insight! though `job.progress()` would only take a Number earlier.

Another issue I came across where I find it confusing in the docs is:
when a job is stalled, it is currently moved to failed jobs by default, where the newly spin up worker would continue taking a job from the active job queue; this leads to a long failed job list when they should be retried.

I've tried `queue.on('stall')`, but this doesn't provide control over moving jobs.

**Comment by zhenyulin** [comment]
furthermore, there's an issue I came across when the job worker instance crash, I can't remove the job from the active queue in Arena. I assume this is due to the job is still locked?

**Comment by manast** [comment]
@zhenyulin stalled jobs are moved back to the wait queue but only if the option ```maxStalledCount``` is above 1. Otherwise the job will fail.
Probably the reason you cannot remove it from active as you mentioned is because it is still locked, but it will automatically be moved to wait or failed the next time the ```moveStalledJobsToWait``` function is executed.

**Comment by stansv** [comment]
@manast,

by the way, I observed that by default jobs are restarted for 1 time in case if they stalled. I've checked the script and it looks like this is true:

https://github.com/OptimalBits/bull/blob/develop/lib/commands/moveStalledJobsToWait-7.lua#L61

Initially there's no `stalledCounter` on a job. When we call `HINCRBY .. 1` the value is set to 0 before the operation is performed, then Redis increases it by 1 and returns 0 + 1 = 1. On the next line we check if `stalledCount` is greater than `maxStalledCount`, and in case when `maxStalledCount` is 1 (default) we do not fail the job.

**Comment by zyf0330** [comment]
Hello, I want to set `maxStalledCount` as `infinity`.
Now I cannot get `maxStalledCount` value in `process(job)`, which exists in `bull:QueueName:jobId` hash in redis. So I cannot ensure if I should create a new job to avoid exceed `maxStalledCount` limit.
