### ISSUE TITLE
Fair queue

### ISSUE THREAD

**Issue by MrNghia123** [OptimalBits/bull#1409]
Hi,
Thanks for a great library.
In my project I use bull as a working queue delivering jobs to distributed workers. The jobs are targeted for different 'clients'.
Currently I can put the jobs in the queue in a FIFO manner. A client with lots of jobs would block others, which sitting idle waiting for their jobs.
I tried putting jobs in LIFO, since my jobs are isolated block of works and order doesn't matter, which helps a bit but does not solve the entire problem, as an aggressive client would still blocking others.
Being able to introduce fairness into the queue would be a great feature.
Regards,

**Comment by stansv** [comment]
Hi, 
what you can do
1) create dedicated queues for each client; you can optionally close queue when all jobs done on "drained" event, but this have some drawbacks
2) alternative approach — prioritized jobs. It will require from you to track how many jobs are created per each client. First job, created for a particular client, should have priority 1 (highest)

Example for [2], suppose you have clients A, B and C and some jobs for them in a queue:

    A - A - A - A - B - C - C - A - A - A - A - B - A - A - A - C

with priorities it will look like

    A1 - A2 - A3 - A4 - B1 - C1  - C2 - A5 - A6 - A7 - A8 - B2 - A9 - A10 - A11 - C3

so that all jobs would be executed as per its priorities

    A1 - B1 - C1 - A2 - B2 - C2 - A3 - C3 - A4 - A5 - A6 - A7 - A8 - A9 - A10 - A11


See the reference https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md for details.

**Comment by MrNghia123** [comment]
That's brilliant, thanks.
For anyone who hit this, I follow the 2 option. I use a Map to keep track of the "current" priority of each clients as suggested by stansv and clear the Map in "drained" event of the queue.
Regards,
