### ISSUE TITLE
Bug: 'global:cleaned' event doesn't trigger

### ISSUE THREAD

**Issue by ks-s-a** [OptimalBits/bull#1430]
## Minimal, Working Test code to reproduce the issue.
```
const Queue = require('bull');
const queue = new Queue('name', redisURI);

queue
  .on('global:cleaned', function () {
    console.log('global:cleaned!');
  })
  .on('cleaned', function () {
    console.log('cleaned!');
  });

queue.process(function () {
  console.log('task was started!');
});
Promise.resolve()
  .then(() => queue.add({}))
  .then(() => queue.clean(0));

```

Expected:
```
cleaned!
global:cleaned!
task was started!
```

Actual:
```
cleaned!
task was started!
```

## Bull version
v3.10.0

## Additional information
I'm sure that the bug related to another: #1421

**Comment by stansv** [comment]
Thanks for reporting a bug! I've posted some answer in #1421 just now, this event is not supported by design. In next major version api is changed so there won't be confusion between local vs global events, since global events now will have their own source. But I believe we can also support global:clean as well.
