### ISSUE TITLE
Not triggering completed event

### ISSUE THREAD

**Issue by Chitzi** [OptimalBits/bull#1452]
### Description
I'm having some trouble with Bull.

What I want to reach is quite simple.

Have a listener program that only process the queues so I can add a new job everywhere I want, for example from a http listener.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

http.js
```
var restify = require('restify');
var server = restify.createServer();
var
  Queue = require('bull'),
  cluster = require('cluster');

server.listen(3010, function() {
  console.log('Search ready for action!');
});

server.get('/', function(req, res) {
  var queue = new Queue("test");
  queue.add();
  queue.on("completed", (j) => {
    console.log("Completed!");
    res.send("Completed");
  });
});
```
queue.js
```
var Queue = require('bull'),
  cluster = require('cluster');

var queue = new Queue("test");

queue.process(function(job, done) {
  setTimeout(() => {
    done();
    console.log("Completed...");
  }, 3000);
});
```

Problem is that, from the logs, it never reaches the callback.

`0|test_multithread  | Completed...`

What I'm missing?

## Bull version
3.10.0

## Additional information
Node v12.6.0

**Comment by stansv** [comment]
There're concept of global events exists used to broadcast any events on physical Bull queue in Redis to every Queue object instance. Attach your listener to `var queue` created in queue.js and it should work. Or use global events and listen to 'global:completed' in your http.js. But do not create Queue instance and attach event callback on every request, do it outside `server.get()`, and reuse queue variable from outer scope. To achieve what you want, you can also create an object or Map in outer scope where a key would be an id of the job (returned if you append `.then((job) => { job.id })` to the `queue.add()`), and value is a callback calling a `res.send()`. So that you can find callback by job id in event handler (passed as 1st arg) and invoke callback. You'll also need to think about some timeout to send error responses to client in order to release connection-related resources.

https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#global-events

**Comment by Chitzi** [comment]
Perfect! Thank you so much for the suggestion.

```
var restify = require('restify');
var server = restify.createServer();
var
  Queue = require('bull'),
  cluster = require('cluster');
var queue = new Queue("test");

server.listen(8053, function() {
  console.log('Search ready for action!');
});

server.get('/', function(req, res) {
  queue.add().then((j1) => {
    queue.on("global:completed", (j) => {
      if (j1.id == j) {
        console.log("Completed!");
        res.send({
          "status": "Completed"
        });
      }
    });
  });
});
```

```
0|test_multithread  | Completed...
1|test_multithread  | Completed!
```

**Comment by manast** [comment]
@Chitzi you are going to leak listeners by doing it like that, please check the "finish" method instead.

**Comment by Chitzi** [comment]
Can't find finish method. Do you have an example?

**Comment by stansv** [comment]
I'm not sure about finish method, but what I suggested should look like this (did not tested)

```
var restify = require('restify');
var server = restify.createServer();
var
  Queue = require('bull'),
  cluster = require('cluster');
var queue = new Queue("test");

server.listen(8053, function() {
  console.log('Search ready for action!');
});

var jobs = {};

queue.on("global:completed", (j) => {
  if (jobs[j]) {
    console.log("Completed!");
    var timeout = jobs[j].timeout;
    clearTimeout(timeout);
    
    var res = jobs[j].res;
    res.send({
      "status": "Completed"
    });
    delete jobs[j];
  }
});

server.get('/', function(req, res) {
  queue.add().then((j1) => {
    var timeout = setTimeout(function() {
      delete jobs[j1.id];
      res.send({
        "status": "error (timeout)"
      });
    }, 60000);
    jobs[j1.id] = { req: req, res: res, timeout: timeout };
  }).catch((error) => {
    res.send({
      "status": "error (" + error + ")"
    });
  });
});
```

**Comment by Chitzi** [comment]
Amazing! Thanks a lot!
