### ISSUE TITLE
Errors in event listeners are silently ignored 

### ISSUE THREAD

**Issue by mosilla** [OptimalBits/bull#152]
By default, [EventEmitter](https://nodejs.org/api/events.html#events_class_events_eventemitter) sends errors that occur in event listeners to an `error` handler if one is registered. Otherwise, it throws. Queue is a subclass of EventEmitter, but it doesn't appear to do either of these things:
### With Error Listener

``` javascript
var Queue = require('bull');
var queue = Queue('test');

queue.add({ foo: 'bar' }).then(function () {
    queue.process(function (job, jobDone) {
        console.log('job:', job.data);
        jobDone();
    });
});

queue.on('error', function (err) {
    console.error('error:', err);
});

queue.on('completed', function () {
    queue.close();
    queue.noSuchMethod();
});
```
### Output

```
job: { foo: 'bar' }
```
### Without Error Listener

``` javascript
var Queue = require('bull');
var queue = Queue('test');

queue.add({ foo: 'bar' }).then(function () {
    queue.process(function (job, jobDone) {
        console.log('job:', job.data);
        jobDone();
    });
});

queue.on('completed', function () {
    queue.close();
    queue.noSuchMethod();
});
```
### Output

```
job: { foo: 'bar' }
```

**Comment by manast** [comment]
Good catch, I actually didn't know that event listeners had this behaviour.

**Comment by evanhuang8** [comment]
I would argue that the current behavior is correct, since the error is encountered within the job processing function itself, which means the job fails to complete, but it doesn't necessarily mean the whole queue has encountered an error. 

One way to improve the silent fail behavior is probably have the `handleFailed` function in `processJob` log out some message and the error stack; the other would let the queue emit an `error` event in `handleFailed`, in addition to the current `failed` event. IMO the former is better.
