### ISSUE TITLE
Create queue for each individual user

### ISSUE THREAD

**Issue by Popesites** [OptimalBits/bull#1567]
I want to create a unique queue for each user. The job for each user will be the exact same, I just basically want each user to not have to wait on other users' jobs to finish, only their own.

So let's say user 1 creates a job for "processDeal", and then user 2 creates a job for "processDeal". They should run concurrently.

Then let's say user 1 creates a second job for "processDeal". This job should wait on user 1's first job to be completed, but it should not wait on user 2's created job whatsoever.

Does this make sense? It seems like this is theoretically possible with the existing library functionality, but I could use help figuring out how to build it. 

I am basically looking to scale a single job / queue horizontally across all users.

**Comment by stansv** [comment]
This depends on how many users you're expect to have. Each queue requires a dedicated connection to Redis. But if number of users is large you can reach out of memory, anyway you should have some limit for how many jobs you can run simultaneously. So I'd try a single-queue setup with many workers (use concurrency setting as well, https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueprocess).

Running jobs sequentially for a particular user can be tricky, how to implement this depends on your case; in general, the single approach I know here is to physically add 2nd job to Bull queue only when 1st is completed — as the final step of 1st job procedure or in `completed` event listener. The idea is to store chains of jobs for each user somewhere (in Redis, database, in memory, etc). In other words, you manage user queues by yourself.

(I spent some time trying to implement similar functionality in my project, but did not finished it as requirements were changed. In my implementation I have user queues as Redis lists, list contains strings with job data (JSONs). User jobs remove itself from user queue after completion, and when user requests to add next job, I check if user queue is empty — in this case job should be added to both user queue and Bull queue, otherwise I only add it to user queue. When job finishes it removes itself from user queue and if there're next job exists in user queue, it is added to Bull queue to run next.)

**Comment by Popesites** [comment]
Thanks for describing this approach. I think it really helped me conceptualize how I will solve what I am looking to do.

If anyone is interested in how I am going to solve it this is roughly what I did:

    router.get('/', async (req, res) => {
        const testQueue = new Bull('test', 'redis');
        const userId = req.body.userId; // unique identifier
        const newQueue = new Queue({
            user: userId,
            processStatus: 0
        });
        await newQueue.save(); // create record in MongoDb for this queue
        const queuesList = await Queue.find({ user: userId, processStatus: { $lte: 1 } }); // find all records that are status 0 (not processed) or 1 (currently processing)
        if (queuesList.length > 1) { // if there are elements in the background that are processing, want to return since we will handle these in complete event
            return res.sendStatus(200);
        }

        testQueue.add(newQueue); // add this process to queue if no other background processes

        testQueue.process(async function (job, done) {
            await axios.get(`https://backend.com/api/some-route?job=${job.id}`);
            done();
        });

        testQueue.on('completed', async (job) => {
            const saveQueue = await Queue.findOne({ _id: job.data._id });
            saveQueue.processStatus = 2; // set status to 2 (completed)
            await saveQueue.save();
            const queuesList = await Queue.find({ user: job.data.userId, 
    processStatus: { $lte: 1 } }); // find any existing queues in mongoDb for requested user
            if (queuesList.length >= 1) {
                const processDeal = queuesList.shift(); // if one is found, pull the first one to add to queue
                testQueue.add(processDeal);
            }
        })
        res.send("Hello World!");
    });

**Comment by stansv** [comment]
OK, creating Bull queue instances in request handler is not a very good idea, https://github.com/OptimalBits/bull/issues/1452

**Comment by manast** [comment]
not a very good idea but at least close the queue when you are done with it or you are going to run out of connections very soon.

**Comment by Popesites** [comment]
> not a very good idea but at least close the queue when you are done with it or you are going to run out of connections very soon.

Do you have any suggestions for how I can build a better solution?

**Comment by stansv** [comment]
Even if so, when two requests are running simultaneously one testQueue instance in your code can start processing the job added by another instance, to avoid this you should use unique Bull queue name for each request. In #1452 I provide a solution to reuse the queue.

I see many people integrate Bull with Express, trying to complete asynchronous task like Bull job within a single synchronous HTTP request. Each time I confused — what was the reason to use Bull for this?

**Comment by patrickbolle** [comment]
I hate to bump this back up; but I am trying to figure out this exact situation. Could someone explain to me *why* creating a new queue on an individual request is not ideal? 

I am looking to do exactly as OP intended; ensuring that queue for customer X doesn't block the same queue for customer Y.

I know BullMQ Pro has the grouping feature, but for my use-case, paying $950 a year for that feature alone doesn't make sense.

As long as I destroy the queue after completion, shouldn't that resolve any issues here?

The example in this comment, I don't think satisfies the need here; the queue is still going to be blocking (or waiting till completion) to start another queue, correct? (https://github.com/OptimalBits/bull/issues/1452)

Once again, apologies for bumping this back up; but having a lot of difficulty figuring out how to solve this. Bull *almost* solves it, but not quite.

**Comment by manast** [comment]
If you create a new queue for every request then it is the same as not having a queue at all...

**Comment by manast** [comment]
@gerardkabre there are some important shortcomings with the solution you propose. First, it is slow to check if a job for a given userId is in the executionQueue (you will need to read one by one every job and check in the data field some property that stores the userId). Secondly, there will be all kind of bad effects in busy queues with many users and many jobs, they will start bouncing around back and forth to the delay status, checking again, and so on... at the end of the day it will not scale.
Thats why we developes groups in the Pro version, precisely because it is quite a hard problem to solve in a robust and efficient way.

**Comment by gerardkabre** [comment]
@manast Indeed commented while thinking outloud and realised how much it sucked after implementing it 😆 nice work with the groups freature looks awesome

**Comment by Siumauricio** [comment]
I found this project that I thought was very good and that solves the grouped queues


https://github.com/Nerimity/Mimiqueue/tree/new

I use this package in [Dokploy Cloud](https://dokploy.com) to handle deployments per each user which solves the problem from this issue!
https://github.com/Dokploy/dokploy/blob/canary/apps/api/src/index.ts#L44

Hope it helps!

**Comment by prabesh412** [comment]
Hi, 
I will like to purpose a solution or rather I will like some insight if my solution is acceptable 
```
const existingDeleteJob = await deleteWebhookQueue.getJob(`job-${id}`);
    if (existingDeleteJob) {
      await deleteWebhookQueue.add(
        "delete-webhook",
        {
        ....data........ ,
        },
        {
          jobId: `job-${id}-${Date.now()}`,
          delay: 3600,
        }
      );
      return res.sendStatus(200);
    }
    deleteWebhookQueue.add(
      "delete-webhook",
      {
        ...............data...................,
      },
      {
        jobId: `job-${id}`,
      }
    );
    
```
    so, I am checking if the queue with that particular job id exist, if it does I will push it to the queue with some delay. 

handler: 
```
 deleteWebhookWorker.on("completed", async (job) => {
  const delayedJobs = await deleteWebhookQueue.getDelayed();
  const nextJob = delayedJobs.find((delayedJob) =>
    delayedJob?.id?.startsWith(`job-${id}-`)
  );
  if (nextJob) {
    await nextJob.remove();
    deleteWebhookQueue.add("delete-webhook", sanitizedJobData, {
      jobId: `job-${id}`,
    });
  }
});
```

The only bottleneck I see is with getting all the delayed job and linearly searching for the job but I could further optimize this by saving the jobs Id's with those timestamp in redis and getting it on this handler. 
but I don't expect this particular service to have much delayed jobs so, if I ever need to scale I will just save the ref of delayed job.
