### ISSUE TITLE
"Error: Missing process handler for job type Queue.processJob" when using custom JobId

### ISSUE THREAD

**Issue by maddygoround** [OptimalBits/bull#1579]
## Description
We are not getting a 'failed' and 'error' event but when looking into Redis for the Job we find the following issues 
#### Missing process handler for job type Queue.processJob. 

We noticed that when we are not using custom jobId the queue works fine and control goes to the right named process but when we set a custom jobId it fails silently.

## Minimal, Working Test code to reproduce the issue.
As told this happens only when we are using custom jobId with named processes.

## Bull version
3.12.0

## Additional information
We are using Bull in nestjs using a custom module called nest-bull

**Comment by manast** [comment]
Custom jobIds are identical to normal job ids, only difference is that one is autogenerated  and the other is given by the user. The error you are getting is raised when you are missing one of the named worker processors in one of the worker instances. In reality is better to not use named processors at all, it is a deprecated feature and in BullMQ is not used anymore, it just creates confusion because people have different expectations of this feature.
