### ISSUE TITLE
If url is undefined options are ignored

### ISSUE THREAD

**Issue by JSRossiter** [OptimalBits/bull#1603]
## Description
If options are passed as the third argument to the queue constructor but the second argument is undefined the options are ignored. My use case is wanting to provide the redis URL via environment variable in production but connect to local redis in development.

## Minimal, Working Test code to reproduce the issue.

```
const queue = new Queue('task', process.env.BULL_REDIS_URL, {
    prefix: 'my_bull_queue'
  });
```

## Bull version
3.12.1

**Comment by stansv** [comment]
Hi! This issue have the same root cause as https://github.com/OptimalBits/bull/issues/1338, the solution is to avoid `url` parameter at all — parse URL just pass queue name and options. In my project I use this modified function originally taken from bull sources, with `rediss://` (ssl) support added:

```
const redisOptsFromUrl = (urlString: string): IORedis.RedisOptions => {
  const redisOpts: IORedis.RedisOptions = {};
  try {
    const redisUrl = url.parse(urlString);
    redisOpts.port = Number(redisUrl.port) || 6379;
    redisOpts.host = redisUrl.hostname;
    redisOpts.db = redisUrl.pathname ? Number(redisUrl.pathname.split("/")[1]) : 0;
    if (redisUrl.auth) {
      redisOpts.password = redisUrl.auth.split(":")[1];
    }
    if (redisUrl.protocol === "rediss:") {
      redisOpts.tls = {};
    }
  } catch (e) {
    throw new Error(e.message);
  }
  return redisOpts;
};
```

**Comment by tvedtorama** [comment]
I was not able to use URLs with the rediss-protocol directly with Bull, and had to use `stansv` function to produce valid redis options for connecting to a TLS-server.  The rediss protocol should be supported by ioredis, so this is a bit weird to me.

**Comment by shem8** [comment]
This is very frustrating since ioredis does support 'rediss' as part of the URL. My workaround was to use `createClient` instead of parsing the URL myself (and change it every time new feature added):
```
new Bull(name, {createClient: () => new Redis(URL)});
```

**Comment by ejarnutowski** [comment]
@tvedtorama, could you please provide an example of code that worked for you?  Just running into this issue now.

**Comment by gdelory** [comment]
I'm having a different but similar issue. I need to use a `rediss:` URL, and a `tls` option to pass to the redis client a CA certificate. I'm stuck because as long as you pass both a URL as second param of the Queue constructor, and some options as 3rd param, the redis default property overwrite everything from the URL as @JSRossiter said, so this doesn't work:

```
const events = new Queue('events', process.env.REDIS_URL, {
  redis: {
    tls: { ca: process.env.REDIS_CA }
  },
  prefix: `thub-${process.env.VERSION_LEVEL}-bull_`,
  defaultJobOptions: {removeOnComplete: true}
})
```
I guess the proper way is to define everything in the redis option (host, port, ...) but since my redis is using username/password auth, this doesn't seem natively supported.

I guess @shem8 work-around would work fine (nice job finding this), but `createClient` is deprecated so I was hoping to find a none-deprecated way

Also tried this since the `redis` property should be passed `as-is` to ioredis according to the doc:

> RedisOpts are passed directly to ioredis constructor, check ioredis for details. We document here just the most important ones.

and ioredis should support (url, opts) according to the [doc](https://github.com/luin/ioredis/blob/master/API.md#redis--eventemitter)

```
const events = new Queue('events', {
  redis: [process.env.REDIS_URL, {
    tls: { ca: process.env.REDIS_CA }
  }],
  prefix: `thub-${process.env.VERSION_LEVEL}-bull_`,
  defaultJobOptions: {removeOnComplete: true}
})
```

But that didn't work because Bull adds its own default option if the redis option regardless if the redis property is an object or not in:

```
  _.defaults(opts.redis, {
    port: 6379,
    host: '127.0.0.1',
    db: opts.redis.db || opts.redis.DB,
    retryStrategy: function(times) {
      return Math.min(Math.exp(times), 20000);
    }
  });
```

I guess the only two ways to to this are to pass everything as options, without using a URL, or use @shem8 deprecated work-around.

To parse the URL, the `redisOptsFromUrl` function in queue.js is a good start to see how it should look exactly. I'll save you the debugging if you also have a rediss: url with username/password, the result for 

`rediss://user:password@hostname:port/0` gives:

```
{
  db: '0',
  host: 'hostname',
  password: 'password',
  port: 'port',
}
```

which surprisingly doesn't care about the username, but that seems to work, so I ended up with:

```
const events = new Queue('events', {
  redis: {
    host: process.env.REDIS_HOST,
    password: process.env.REDIS_PWD,
    port: process.env.REDIS_PORT,
    tls: { ca: process.env.REDIS_CA }
  },
  prefix: `thub-${process.env.VERSION_LEVEL}-bull_`,
  defaultJobOptions: {removeOnComplete: true}
})
```
I'm still a little worried that might break at some point since it's not using the username and the auth scope with user/password is new in redis 6, and I'm thinking it might be a fallback for retro-compatibility which might go away at some point?

**Comment by manast** [comment]
Any changes now will be a breaking change for many so despite the current limitations and inconveniencies I think it is better to leave it as is. In BullMQ this has been addressed properly.

**Comment by manast** [comment]
(of course if somebody wants to contribute with a PR that can solve the issues in a non-breaking manner I will happily merge it)
