### ISSUE TITLE
job.update inside sandbox processor 

### ISSUE THREAD

**Issue by thbl** [OptimalBits/bull#1608]
is there any way to use the job.update inside a processor ?

**Comment by douglascayers** [comment]
@thbl in a sandboxed process, you are literally running in a separate process with a different memory model, so the `job` object your processor is given is a JSON deserialization of some of the data a job represents, but completely detached from the actual queue itself.

When using a non-sandboxed processor, the `job` instance you get is part of the same memory model as the queue is running in and so you have the ability to `job.update(..)` and `job.remove()` and some other methods.

Because of this, you may need to propose a new function on the sandboxed job like I did for supporting `job.progress()` per https://github.com/OptimalBits/bull/pull/1536/files

Note that for the sandboxed process to communicate back to the master process where the queue exists then a message has to be sent between the two processes, often as a JSON serializable string. This also means the function calls to update the job would be asynchronous in a sandboxed process.

For my own project, I've been toying with idea of running a little express web app that my sandboxed processors can callout to like a little REST API that would perform job functions on the queue on my behalf rather than keep adding patch functions to the job object my sandboxed processor receives.
