### ISSUE TITLE
How to add time between next Job queue?

### ISSUE THREAD

**Issue by haxtordotid** [OptimalBits/bull#1611]
Hi, Sorry for asking here, i'm new in Queue Bull and Nodejs

I want to add 5 second before next queue execute, but it seem immediatly executed
i think when i add delay option it can make delay between next queue

How i can achive that?

Here my code
![image](https://user-images.githubusercontent.com/56084255/72260658-ea505d00-3645-11ea-8a06-24aaffa4954f.png)

**Comment by stansv** [comment]
There can be multiple working approaches depending on you setup and needs, you can use bull `delay` option but only if you add 2nd job inside 1st one, just before job callback returns — since delay is calculated from a moment of time when `queue.add()` function is called, you cannot add delayed job in advance as you do not know when worker will take it from queue. And this approach has a lot of disadvantages, for example it won't work well if you have multiple workers (cluster), if job is retried etc.

In my project we use bottleneck library (https://github.com/SGrondin/bottleneck) to add delays between api calls inside our jobs, so this might work for you. It uses Redis and thus supports clusters.
