### ISSUE TITLE
finding out job state

### ISSUE THREAD

**Issue by punund** [OptimalBits/bull#162]
Is there a documented way to figure out if a job is "active", or "waiting"?

**Comment by albertjan** [comment]
@punund there is no "fast" way to find out if a job is active or waiting because these are redis lists. You can however fairly easily ask from the queue which jobs are waiting and which are active.

https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L601-L607

You should be able to figure out the rest :wink:

**Comment by kulbirsaini** [comment]
Though it's going to be very expensive, will you guys consider if I provided a patch with this functionality?
