### ISSUE TITLE
Unable to catch job processing events when using separate process

### ISSUE THREAD

**Issue by aksharj** [OptimalBits/bull#1723]
Hi,

It might not be a issue but i am unable to find an answer to my question so i am positing it here.
I need to catch certain events on the queue like completed, failed, error.

I am trying to have a separate process for process function, but the problem is after moving the job processing to a process function i am unable to catch any of the event like completed, failed, error. Before when there was no separate process, i was able to get these events.

Below is my code
```
processor.js
module.exports =  async function(job, done) {
  try {
    await processExport.performExport(job.data.params, done);
  } catch(err) {
    console.log(err);
    console.log('in error handling');
  };
}
```
worker.js
```
const csvExportProcessing = require('../queue');
csvExportProcessing.process(5, __dirname + '/processor.js');

csvExportProcessing.on('completed', function(job, result){
  console.log('job is now completed');
});

csvExportProcessing.on('failed', function(job, err){
  if(job.attemptsMade == job.opts.attempts) {
    //send a postback
  }
});


csvExportProcessing.on('global:error', function(job, err){
  console.log('Is last attempt?  => ', (job.attemptsMade === job.opts.attempts));
});
```
May be i am doing something wrong, any help on how can i catch the events will be really helpfull.

Thanks.

**Comment by rendrrlabs** [comment]
Hello. Even I'm stuck at this point. below is my questions regarding similar topic, but I was not able to get any asnwers in StackOverflow community.
https://stackoverflow.com/questions/61786093/use-nodejs-bull-queue-seperate-processor

I guess, Its a dead end. We need to handle the job process completely in processor.js since that file acts as completey different Server only.
Bull wil push the process to that file and done, no more connection between those jobs. I'm still trying to get the issue sorted and digest Bull documentation, Bull documentation is not clear on this topic so many people are stuck at this.

**Comment by manast** [comment]
I am not sure I understand the issue, why can't you just listen to the global events?
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#global-events
