### ISSUE TITLE
Delays, concurrency, limiters, oh my! (question)

### ISSUE THREAD

**Issue by gcleaves** [OptimalBits/bull#1779]
Hello. My goal is to run multiple jobs concurrently but staggering each job launch because start up is resource intensive. I thought I could use the Rate Limiter or Delay to accomplish this, but I am not able to.

I have job processors spread across multiple servers. Multiple jobs are added to the queue at the same time by a single server. I want each job processor to run multiple jobs concurrently, but I want to stagger the job launch. Is this possible?

For example, I'd like to add 10 jobs to the queue and have each job processor start grabbing and launching a job every 5 seconds, with a max of 5 jobs running concurrently per job processor.

Thanks in advance for your help.

**Comment by suchakraborty** [comment]
I am new to bull but I am enjoying using it, so, let me take a stab at this. I am sure somebody with more experience will correct me if I am wrong.

job processors themselves do not run things in parallel, but you can ask Bull to have up to n job processors. If you notice the method signature of a processor it gets 1 job in argument.

To make things a little easier to talk about, let me change your example's numbers a little bit 
So I assume you mean you have, say a 100 servers running the same code pointing to 1 Redis and you want to process up to 5 jobs at a time on each server (so 500 jobs) and you want to start them at least , say, 10 seconds apart.

So concurrency is a Processor parameter - ie. this controls how many will be processors will be running at a time.  = 5
Rate limiter is a queue parameter ie. the nozzle/faucet that processors are tapping from - so this will be limit of max 1 duration 10000 ms. i.e. 1 every 10 seconds. As far as I understand it - this is only per running instance of bull. i.e. there will be up to 100 jobs released total across all 100 servers every 10 seconds.

Feel free to feed the queue from anywhere at any speed as long as you have a big enough Redis (otherwise change your job definition to contain pointers to where to grab real job data from.)

Finally, if this does not work for you, another option is to have a repeatable job with a cron that feeds the queue slowly too. This trick involves either the cron-ed job's queue or from one of its event handlers to add n jobs to your main queue. 

Overall - as a comment to your post's heading - yes bull gives you different types of bullets - and no they are not meant to be shot at your foot, but at different types of targets.

Based on my limited experience so far, Bull settings out of box are well tuned for smaller jobs. With larger long running jobs, you have to learn a bit more - e.g. I am taking database backups and running into 'issues that appear to be stemming from settings Bull uses to identify stalled jobs, etc. So heads up, as you mentioned heavy jobs.

All the best and post back here if it works/does not work for you.

**Comment by manast** [comment]
@suchakraborty thanks for answering. Regarding rate-limiter, it is not per bull instance, it is for the queue globally, that allows you to have as many processors as you want and still being able to define a global limiter. A PR that is in the works will allow to have different rate limiters per queue based on a job data field though: https://github.com/OptimalBits/bull/pull/1753

**Comment by suchakraborty** [comment]
Wow Thanks @manast This is great!
