### ISSUE TITLE
queue.empty() does not seem to be working

### ISSUE THREAD

**Issue by niftylettuce** [OptimalBits/bull#1792]
I have a script that does `queue.empty()` followed by `queue.add()` in serial for a job that is recurring.

For some reason, the queue is not actually emptied, and all previous recurring jobs are still there (possibly locked/stalled).

This causes major issues obviously as the queue cannot complete and no jobs can be processed.

Source: https://github.com/forwardemail/forwardemail.net/blob/master/bull.js
Ref: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueempty

**Comment by niftylettuce** [comment]
I have created `bree` as an alternative https://github.com/breejs/bree.

**Comment by manast** [comment]
@brunnerlivio for the record, there are no PRs that do not get merged due to personal conflicts. PRs are accepted if they are approved strictly based on its technical merits and if they fit in current codebase and design. What is not acceptable is complaining that feature X does not work (without any example code or similar), and if you do not fix it then your library is unstable and you should use my library instead. I will not tolerate misinformation in the spaces I control, thats the best for everybody in my opinion.

**Comment by BrunnerLivio** [comment]
@manast Thanks for shedding some lights from your PoV. 
In my comment I was not refering to “personal conflicts”, but rather just “conflicts” from a technical space. I simply tried to summarize what I found interesting whilst doing a quick research on this topic - tried to be objective (slightly altered my comment and added a disclaimer)

With that being said the NestJS team have been very happy users of Bull so far and we really appreciate your outstanding effort.
I very well know its a sensitive topic, so I hope we will find a solution which fits us all best.
Glad to see you are all active and caring about delivering the best possible library, even if certain opinions divide.
