### ISSUE TITLE
Proper sandbox subprocess count

### ISSUE THREAD

**Issue by chaffeqa** [OptimalBits/bull#1820]
## Description

We have x2 queues, trying to use the same Pod to listen to both with sandbox workers, code as follows:
```tsx
const queues = this.getQueues()
    const maxSubprocessesTotal = os.cpus().length - 1
    const maxSubprocessesPerQueue = maxSubprocessesTotal / queues.length
    for (const queue of queues) {
      const subProcessCount = Math.max(
        1,
        (queue.name === defaultQueueName && Math.ceil(maxSubprocessesPerQueue)) || Math.floor(maxSubprocessesPerQueue),
      )
      const rootDir = process.env.PWD
      const filePath = settings.NODE_ENV === "production" ? `${rootDir}/build/process-job.js` : `${rootDir}/bin/dev-process-job.js`
       queue.process("*", subProcessCount, filePath)
    }
```

With a single queue, we simply did `CPU cores - 1` (1 being "master" process).  However if we are listening to x2 queues, does that mean the max number of processes for the Pod needs to be a combination?

```tsx
// CPU cores: 4
// Master: 1 process
// --- A ----
// Queue 'Default': max subprocesses: 2
// Queue 'HighPriority': max subprocesses: 1
// --- B ---
// Queue 'Default': max subprocesses: 3
// Queue 'HighPriority': max subprocesses: 3
```

Which one of the above would result in saturation?

**Comment by manast** [comment]
Bull will create a new process for every "subProcessCount" you specify. However I do not think you need to match the number of CPU cores with the number of processes for a number of reasons. First because in any OS processes are not guaranteed to run each in a different CPU core. But sure it also depends on what kind of process you are running, if it is very CPU intensive or more IO intensive. I recommend that you monitor your CPU usage under heavy load and finetune the concurrency argument so that the CPU is most of the time below 70%.

**Comment by chaffeqa** [comment]
Thanks a ton for the information!

Yea I think the biggest question was answered: Option `A` above will generate the `4` processes max.

As for the maxing of the CPU, completely agree that it's more of a per-use-case question.  We are using AWS ECS, so docker with a XL ec2 instance, leading to availabe 4 cores, but that doesnt me running x4 processes will saturate.  It's a really tricky question, but understanding how Bull works helps reduce that to the real question of `how many sub-processes do we desire per worker instance`

Thanks 💯! I love your responsivesness!
