### ISSUE TITLE
Question: Lock duration meaning

### ISSUE THREAD

**Issue by adame21** [OptimalBits/bull#1826]
Hi, 
I have a question about locks and specifically lock duration and renewal
I know this might be somewhat off topic, sorry, I'll be happy to get basic answers.

1. Why are locks even needed? 
2. Why wont I set the lock duration to the job's timeout ? just lock it once for the duration of the process. will something bad happen from this ?
3. What will be the consequences of setting a lock renew of 1/10 of lock duration? why is it 1/2 by default?

I'm sorry if these questions are ignorant, I am trying to understand a little better since I have been having stalled jobs issues for a long time, and im trying to find the optimal queue settings for me.

Thanks for this wonderful lib :)

**Comment by manast** [comment]
>1. Why are locks even needed?

So that no other worker would work on the same job.

>2. Why wont I set the lock duration to the job's timeout ? just lock it once for the duration of the process. will something bad happen from this ?

Not sure what you mean with this. The lock is active while the worker is processing the job. However if the worker crashes, the lock will automatically "unlock" after "lock duration", otherwise the job would be locked forever.

>3. What will be the consequences of setting a lock renew of 1/10 of lock duration? why is it 1/2 by default?

It is a safe enough value.
