### ISSUE TITLE
Restart all queue processing on app restart

### ISSUE THREAD

**Issue by mayuuh** [OptimalBits/bull#1882]
## Description
 am creating a queue and adding a job inside my API.

I am also starting processing my job on API call.

```
const newQueue = createQueue(queueName, opts);

newQueue.add('JokesJob', data, options);

newQueue.process('JokesJob', async (job) => {
            data.jobId = job.id;
            await work(queueName, job.id, 'http://localhost:4045');
            job.progress(5);
        });
```
But when I restart my app. The queue should start processing on the job schedule.

How can I restart all my queue for processing after an app restart?

Thanks

## Bull version
3.18.0

**Comment by manast** [comment]
Not sure what you mean with "restart all my queue". The queue is persisted in redis so when you restart you app all the queued jobs will be there until you process them.

**Comment by vincentpham13** [comment]
I reopen this because i have similar issue but slightly different. 
I have 1 queue and 2 jobs, after terminating the node process and run again, these job does not run immediately. There's a bit delay (exactly 60s, sometime 30s) to get the job running
<img width="230" alt="image" src="https://user-images.githubusercontent.com/63580042/210300921-b56fb87d-1527-497c-8170-a91c82d516e3.png">
<img width="221" alt="image" src="https://user-images.githubusercontent.com/63580042/210300988-2deae3e9-e964-491c-9414-ab82d69ea93c.png">

This is the config for these two jobs 
```js
{
   defaultJobOptions: {
       attempts: 3,
           backoff: {
               type: 'exponential',
               delay: 1000,
           },
      },
   removeOnComplete: true,
   removeOnFail: true,
}
```

**Comment by manast** [comment]
The default expiration time of locks for jobs is 30 seconds, so that would be the maximum amount of time the queue will wait until marking the jobs as stalled and moving them back to the wait status. You can tweak this value, but I would not advise to do so.
