### ISSUE TITLE
queue.add options gets overriden by defaultJobOptions

### ISSUE THREAD

**Issue by otaviosoares** [OptimalBits/bull#1904]
I have a code like the following and I expected the options passed to `queue.add` to have priority over queue's `defaultJobOptions`. However, as for now, if you have an option on `defaultJobOptions` it will always override anything you have in your `add` call. This was very confusing and it took me some time to figure out why it wasn't working.

```js
const queue = new Queue('test', {
  defaultJobOptions: {delay: 10000 } 
});
queue.add('job', {}, { delay: 1000 });
```

**Comment by swayam18** [comment]
We have the same issue. Default job options are being treated as 'mandatory' job options, which is semantically incorrect

**Comment by swayam18** [comment]
The regression was introduced here: https://github.com/OptimalBits/bull/commit/ac2fc51c2b8f544a150b83e5969654f5af8de5f7#diff-afa7a0a70da4b0fa42349adcdb862c6f079f980b4051ca651d929290f34a29c7L706-R705

A temporary workaround is to revert back to bull 3.15.x, but you might have to deal with bugs that were fixed in newer branches
