### ISSUE TITLE
Is addBulk more performant or just a convenience method?

### ISSUE THREAD

**Issue by rosslavery** [OptimalBits/bull#1929]
## Description

Subject is fairly self-explanatory, but just looking for an answer here. @manast ? 

We have "parent" jobs that loop through thousands of array items and add "child" jobs. Is there an advantage to preparing an array of jobs and calling `addBulk`, or is it effectively the same thing as making individual calls to `add` as we loop?

Looked at [the source](https://github.com/OptimalBits/bull/blob/develop/lib/job.js#L103), but not 100% clear on whether the `multi` client being used will help/hurt performance with it being run inside a [transaction](https://github.com/luin/ioredis#transaction)

Happy to make a docs PR clarifying this once I get an answer.

Thank you!

**Comment by manast** [comment]
I have actually not run a benchmark on bull, however I have a prototype implemented as a native redis module and surprisingly (or at least for me it was surprising) adding in batches was not much faster than adding in parallel even with 1 connection. I assume similar results can be expected by addBulk.

**Comment by manast** [comment]
speaking of which, the native redis module is insanely fast, I will release it soon...

**Comment by rosslavery** [comment]
As a follow up...

Is there any recommendations you would make around the number of simultaneous calls to `add`? Versus using something like Blurbird.map with concurrency setting to limit the number of jobs that can be added in parallel?

The native module sounds great! I'm assuming that's Redis 5.0 only and/or BullMQ only?

**Comment by manast** [comment]
In my tests more than 300 parallel calls does not improve performance, but I use only one connection, If I have time I will create a better benchmark suite that tests other more realistic scenarios with several connections running in several machines.
The redis module since it is native does not require any particular library, however I plan to implement a wrapper on top of the module so that you can benefit from performance and other features with the same interface as in bull/bullmq

**Comment by rosslavery** [comment]
Thanks for the answers, looking forward to the native module!
