### ISSUE TITLE
Errors/Exceptions ignored

### ISSUE THREAD

**Issue by palamccc** [OptimalBits/bull#218]
In following example, I'm returning a data which contains circular reference, so it can't serialized. Bull is not handling this error and running the job in infinite loop. Ideally the following job should fail, by throwing error that , return value can't be serialized.

```
var Queue = require("bull");
var q = Queue("bullbug", 6379, '127.0.0.1');

q.on("error", function(err){ console.log("error", err) });
q.on("failed", function(job,err){ console.log("failed", job.jobId, err)});

q.process(function(job){ 
  console.log("hello", job.data);
  var circular = {};
  circular.x = circular;
  return Promise.resolve(circular);
});

q.add("john");
```

**Comment by manast** [comment]
I agree that it should fail if the obj cannot be stringified, but the fix you propose create other problems...

**Comment by palamccc** [comment]
With my fix, tests were also failing :-1: Please fix it, whenever you get time. thanks.

**Comment by alexbeletsky** [comment]
I also detected this issue and see it as major. I spent some time, trying to undestand why nothing happens, only after awhile I noticed typo in my function.

**Comment by manast** [comment]
@alexbeletsky not sure what your case is. If a worker does throw an exception, then the job will fail, of course unless your own code swallows the exception, we have a unit test for this case: 'process a job that throws an exception'. If this is not the case and you are referring to something else, I am very interested to understand the case and make a fix for it.

**Comment by alexbeletsky** [comment]
@manast my case is,

```js
var bull = require('bull');

var queue = bull('some:task');

queue.process((job, done) => {
    console.log('queue.process called');
    setTimeut(() => done(null, { someResult: 2 }), 1000);
});

queue.on('completed', (job, result) => {
    console.log('completed client', job.data, result);
});

queue.on('error', (err) => {
    console.log('error client', err);
});
```

Notice, `setTimeut` misspelled. In console I can see `console.log('queue.process called');` and that's it, no errors, no error handler is called. That could lead to a stupid-hidden bugs.

**Comment by manast** [comment]
you need to listen to the 'failed' event.

**Comment by alexbeletsky** [comment]
@manast Tnx!

**Comment by alexbeletsky** [comment]
Out of curiosity: why to distinguish between `failed` and `error` events? why not just `err` as `(err, jobId) => {}`.

**Comment by manast** [comment]
because failed is for failed jobs, while error is for all kind of errors, such as connection errors, errors executing commands in redis, etc.

**Comment by julianfresco** [comment]
@manast, if you set your job to retry 10 attempts before failure, what events are triggered with 10 unsuccessful attempts? 10 fail events? How would you distinguish the last fail for the job?

**Comment by julianfresco** [comment]
Ah, disregard, I've answered my own question:

    queue.on('failed', function(job, err){
      console.log('Is last attempt?  => ', (job.attemptsMade === job.opts.attempts));
    });

**Comment by autocorrectoff** [comment]
@manast does the `error` event act like a global error handler? will it catch all exceptions my app throws?

**Comment by manast** [comment]
@autocorrectoff no, mostly the ones coming from redis.

**Comment by Hoss3770** [comment]
I am not sure if my case is already answered 
In my case for example I parse files in a loop and then a parse error happens. 
Then the job stays in active an blocks all other jobs from running. 
I never run the `done()` function because the code does not reach this line when the error happens. Does it have sth do to with not calling `done()`?
Or should it also be handled with `on('failed')` and `on('error')`? 
And what does this part of the documentation mean "handled correctly"? 
From the readme in on the repo
```javascript
// If the job throws an unhandled exception it is also handled correctly
  throw new Error('some unexpected error');
 ```
thank you

**Comment by manast** [comment]
@Hoss3770 If you are using the done callback you must call it with the error object if there are errors, otherwise the job will never fail by itself.

**Comment by Hoss3770** [comment]
Thank you 
perfect 
Can you also answer two questions? 
1. can you just explain what is meant by this part in the documentation? 
```javascript 
// If the job throws an unhandled exception it is also handled correctly
  throw new Error('some unexpected error');
  ```
2.  and if an event will be fired when an exception is thrown?

**Comment by Hoss3770** [comment]
Another question regarding this 
If an exception is thrown, it should block only the queue the exception was thrown on right? Because other queues should work concurrently by default. 
Because this is not the behaviour I am getting.

**Comment by manast** [comment]
An exception does not block the queue, it just fails the job that threw the exception.

**Comment by manast** [comment]
I cannot answer those questions with a succinct test code that reproduces the issue. If you can provide one we will look into it in detail, most likely not a bug in Bull.

**Comment by Hisa1998** [comment]
I'm encountering a similar issue to @Hoss3770 with `bull`. It seems that the errors are not being handled by `bull`, causing all scheduled events to get stuck in the waiting queue indefinitely. I have provided a code example to demonstrate the problem:

```javascript
const bullTestQueue = new Queue("bullTestQueue");

bullTestQueue.process(async function (job, done) {
  console.log("bullTestQueue job is working", new Date(), {
    params: job.data.params,
  });
  bullTestFunction(job, done);
});

const bullTestFunction = async (job, done) => {
  console.log(job.data.params.data.id);
  done();
};

exports.scheduleRandomEvents = async () => {
  await bullTestQueue.add(
    { params: { data: { id: 1 } } },
    { delay: 10000 } // 10 seconds in milliseconds
  );
  await bullTestQueue.add(
    { params: { data: { id: 2 } } },
    { delay: 15000 } // 15 seconds in milliseconds
  );
  await bullTestQueue.add(
    { params: { data: null } },
    { delay: 20000 } // 20 seconds in milliseconds
  );

  await bullTestQueue.add(
    { params: { data: { id: 3 } } },
    { delay: 25000 } // 25 seconds in milliseconds
  );
  await bullTestQueue.add(
    { params: { data: { id: 4 } } },
    { delay: 30000 } // 30 seconds in milliseconds
  );
};
```
In this code example, there is a job scheduled with a 20-second delay and a null value for the data field, which should result in an error. However, the expected behavior of bull should be to run the other four jobs and consider the third one as failed. Unfortunately, this behavior is not occurring.

I have attached three screenshots of the bull monitor to provide more context:

The first image shows that there are 5 delayed jobs in the delay queue. [View Image](https://github.com/OptimalBits/bull/assets/48384235/737b630a-8871-44bf-b6ea-af3e8111b71c)

The second image demonstrates that the job with the null data got stuck in the active state. [View Image](https://github.com/OptimalBits/bull/assets/48384235/0bf189a2-aac3-4887-9301-a1d83f54fbe9) ,here you can find the error logged in the console. [View Image](https://github.com/OptimalBits/bull/assets/48384235/3a6f55df-bb91-4c11-a1bf-14b4a2074021)

In the last Image, the two remaining jobs are waiting indefinitely in the waiting queue. [View Image](https://github.com/OptimalBits/bull/assets/48384235/322fa57b-f0ac-4bcb-94c9-2d2cc8bb114c)

It would be greatly appreciated if someone could provide insights on why the errors are not being handled properly and suggest a possible solution or workaround. Thank you!

**Comment by manast** [comment]
@Hisa1998 you are mixing the "done" callback and an asynchronous (async) call, you must just one or the other, not both.
