### ISSUE TITLE
Using a redis instance with enableReadyCheck or maxRetriesPerRequest is not permitted.

### ISSUE THREAD

**Issue by OliverwengFiltered** [OptimalBits/bull#2186]
getting this error after upgrading to latest v4.

i'm using ioredis.

any insights?

**Comment by KishanKumarNR** [comment]
I am alredy using these 2 flags in the config 
 maxRetriesPerRequest: null,
  enableReadyCheck: false

but after upgrade to  I also get an same error

Init server failed:  Using a redis instance with enableReadyCheck or maxRetriesPerRequest is not permitted.

**Comment by manast** [comment]
This is the code that generates that error:
```ts

      if (
        client.options.enableReadyCheck ||
        client.options.maxRetriesPerRequest
      ) {
        throw new Error(errors.Messages.MISSING_REDIS_OPTS);
      }
```

**Comment by jujaga** [comment]
We have those two parameters set as well for the redisOptions so that ioredis knows to instantiate with those settings. We've observed that it seems to behave if we connect to a standalone instance of Redis, but it is now failing to do so with a manually defined Redis.Cluster instantiation, even though we are definitely passing those parameters into the cluster definition as well. We had to rollback to a pre-4.x version because of this issue.

**Comment by tjhelsel** [comment]
I'm having this issue as well when trying to run it with a Redis Cluster.

The problem is that the check that the ClusterOptions shape is different from what is checked in the code that @manast linked:

> This is the code that generates that error:
> 
> ```ts
>       if (
>         client.options.enableReadyCheck ||
>         client.options.maxRetriesPerRequest
>       ) {
>         throw new Error(errors.Messages.MISSING_REDIS_OPTS);
>       }
> ```

The `client` for clusters looks like the below; `maxRetriesPerRequest` and `enableReadyCheck` are on the nested `redisOptions` property, rather than on `options` itself: 
```ts
{
  options: {
    redisOptions: { maxRetriesPerRequest: null, enableReadyCheck: false }
}
```

It looks like reverting to an older version is the best option at the moment, but wondering if a fix is in the works?

**Comment by OliverwengFiltered** [comment]
Hi @manast 

do you mind elaborate a bit on what's changes in v4.1.4, it looks like when I initialize my redis instance I still have to put the below two props in place, otherwise it throws the same error.

```javascript
        return new Redis(process.env.REDIS_URL, {
            maxRetriesPerRequest: null,
            enableReadyCheck: false
        });
```

**Comment by manast** [comment]
@OliverwengFiltered can you provide a test? because in our unit tests we do not specify these options and the tests are passing.

**Comment by OliverwengFiltered** [comment]
@manast 
I put together a very simple demonstration to indicate that the two props seem still needed. 

https://github.com/OliverwengFiltered/bull-redis-demo

just clone the above repo and `npm install && node worker.js`

you will see the error `Using a redis instance with enableReadyCheck or maxRetriesPerRequest is not permitted.` still showing up.

**Comment by tjhelsel** [comment]
> Hi @manast
> 
> do you mind elaborate a bit on what's changes in v4.1.4, it looks like when I initialize my redis instance I still have to put the below two props in place, otherwise it throws the same error.
> 
> ```js
>         return new Redis(process.env.REDIS_URL, {
>             maxRetriesPerRequest: null,
>             enableReadyCheck: false
>         });
> ```

These properties must still be set to a falsy value; v4.1.4 did not change that. The issue that [v4.1.4 fixed](https://github.com/OptimalBits/bull/commit/071c51d16db58ed9f71138058dbbc25f73383e56) is how this check is handled for Redis clusters. Previously, setting the above values to `null` and `false` would not avoid the error for Redis clusters; but with v4.1.4, the error is not thrown. (This has to do with the shape of the cluster options config, per my previous post.)

**Comment by manast** [comment]
@OliverwengFiltered as explained above, if you are instantiating your own Redis instances you need to pass the maxRetriesPerRequest and enableReadyCheck options, you are not doing that here: https://github.com/OliverwengFiltered/bull-redis-demo/blob/main/redis.js

The reason for this requirement is that these settings are necessary for ioredis to actually keep the connections working in all cases even when servers go down, etc. Otherwise, people report these issues as bugs in Bull which is quite time-consuming.

**Comment by OliverwengFiltered** [comment]
@manast 
I see what you are saying, thanks for the explanation.

**Comment by koresar** [comment]
Nice fix Manuel.
I almost reported the bug myself. :) Thanks for this warning in the console. Otherwise, I would have never found this little fact that IORedis disconnects!

**Comment by detunjiSamuel** [comment]
> @OliverwengFiltered as explained above, if you are instantiating your own Redis instances you need to pass the maxRetriesPerRequest and enableReadyCheck options, you are not doing that here: https://github.com/OliverwengFiltered/bull-redis-demo/blob/main/redis.js
> 
> The reason for this requirement is that these settings are necessary for ioredis to actually keep the connections working in all cases even when servers go down, etc. Otherwise, people report these issues as bugs in Bull which is quite time-consuming.

i tried this but it still not gives the same error .

**Comment by abustya** [comment]
> if you are instantiating your own Redis instances you need to pass the maxRetriesPerRequest and enableReadyCheck options

@manast I think this should be documented, somewhere here: https://docs.bullmq.io/guide/connections
Also, the provided example for "Reuse the ioredis instance" is missing these options.

**Comment by manast** [comment]
@abustya you are currently getting an error/warning if using the settings incorrectly, so it should be clear enough I think 🤔
