### ISSUE TITLE
When providing wrong redis credentials, no error is thrown

### ISSUE THREAD

**Issue by paulintrognon** [OptimalBits/bull#2210]
## Description

When using non-existing host or port for redis, no error is thrown: the code just stops for one full hour; when I expected something like an ECONNREFUSED

## Minimal, Working Test code to reproduce the issue.

```js
const Queue = require('bull')

var audioQueue = new Queue("audio transcoding", {
  redis: {
    port: 1234,
    host: "foobar",
    enableOfflineQueue: false, // This option does not appear to change anything
    connectTimeout: 1000
  },
});

audioQueue
  .add({ video: "http://example.com/video1.mov" })
  .finally(() => {
    console.log("I will never be called");
  });
```

## Bull version

4.1.0

## Additional information

I could reproduce this issue in 2 seperate ubuntu environment: my laptop + a remote server.

**Comment by manast** [comment]
Yeah, this is basically when we have to choose between 1) a service that never dies even if the redis instance is temporarily down or 2) if the service should die when this happens. We need to support 2 otherwise we end with services that stop working in the case of transient errors. However, you can still detect there are connection errors, but you need to use an error listener:

```ts
audioQueue.on("error", (err) => {
    console.error(err);
})
```

**Comment by paulintrognon** [comment]
Thank you very much for taking the time to reply.
