### ISSUE TITLE
Understanding in depth how processes/sandboxes work

### ISSUE THREAD

**Issue by Tinadim** [OptimalBits/bull#2319]
## Description

I have a question about https://github.com/OptimalBits/bull#separate-processes. Currently I don't use such strategy, but the idea of better utilization of CPU, less connections to redis and prevention of stalled jobs is very tempting. I do, however, have some concerns and I'd like to understand a bit better how things work under the hood. For example, how is the processor sandboxed? Is it it some kind of fork or child process? 
Currently, my biggest concern is that some of my processors need to perform queries to the database to find the entities they need to process, and I wonder if too many additional processes wouldn't cause too many additional connections to my main database.
What is recommended for such scenarios?

I did some research in the existing issues but couldn't find guidelines or details for scenarios like the one I described above (where jobs need to connect to the database) or in-depth explanations on how the sandboxing and separate process work. Feel free to close this issue if this was covered elsewhere.

## Bull version
I'm using `bull@4.2.1`

**Comment by rosslavery** [comment]
Just to summarize yes they are child processes. It's very difficult (impossible?) to share things like DB processes between threads since they are isolated by design.

In practice we found that the overhead of DB connections was quite low and was worth this trade off to gain the other benefits of sandboxed processors.

**Comment by Tinadim** [comment]
@rosslavery thanks for the response! One follow up question: how does concurrency come into play? For example, lets say that I have two queues like:

```
queue1.process(100, 'path/to/job-1.js')
queue2.process(50, 'path/to/job-2.js')
```

Would that imply that at a given moment I could have 150 child processes running in parallel (and possibly 150 connections with the database) ?

**Comment by rosslavery** [comment]
You're welcome :)

To your second question -- that's my understanding, yes. Hypothetically if each job made 1 DB connection you'd end up with 150. If each job made > 1 connection (e.g. 20+), you could use connection pooling to avoid a runaway connections situation if that concerns you. But in that case each process would get it's own pool since they are fully isolated in that regard.

If I'm off-base here, happy to be corrected. CC @manast

**Comment by Tinadim** [comment]
@rosslavery once again, thanks for the clarifications. One final question is: can you clarify what is the isolate process lifecycle? I tested it locally and noticed that we have a number of processes equal to the desired concurrency and the processes are then re-used (for example, if you have 500 tasks and concurrency of 100, you get 100 processes, but they stay alive and the next 400 tasks re-use those processes). But do they die at some point, or do they stay alive for as long as the parent process?

**Comment by rosslavery** [comment]
That I'm not totally clear on myself. Don't have time to dig into the source right now, but you are correct about how child processes can be re-used. I don't believe they stay alive based on the parent, I think there is some sort of timeout, but I could be mistaken.

**Comment by manast** [comment]
@Tinadim the processes are alive unless they crash, in that case, a new one will be created. So the processes are always reused, this is because creating a new process is time-consuming.
