### ISSUE TITLE
Traces instrumentations

### ISSUE THREAD

**Issue by Doron-Bargo** [OptimalBits/bull#2338]
Hi
Any plans to add native support for tracing instrumentation ( for example opentelemetry ) ?

**Comment by manast** [comment]
No.  Whats the use case for this?

**Comment by afishler** [comment]
Use case is that OpenTelemetry is now frequently used to gain more visibility into micro services based systems.
More and more libraries add built-in auto instrumentation to allow this visibility.
A component such as your queue - prevents the end-to-end visibility because context cannot propagate unless manually added.

Some references:
https://www.aspecto.io/blog/how-to-achieve-end-to-end-visibility-into-redis-pub-sub-using-opentelemetry/

Kafka has this built in:
https://www.splunk.com/en_us/blog/devops/distributed-tracing-for-kafka-clients-with-opentelemetry-and-splunk-apm.html

**Comment by manast** [comment]
Do you have an idea on how OpenTelemetry, for example, would work with bull and/or how it would be integrated?
