### ISSUE TITLE
[feat] IoRedis v5 support

### ISSUE THREAD

**Issue by robertsLando** [OptimalBits/bull#2353]
Is it possible to make bulljs supporting ioredis 5?

**Comment by manast** [comment]
What would be the benefit?

**Comment by robertsLando** [comment]
I have some packages in my application that support it but I cannot update them until also bulljs supports it

**Comment by manast** [comment]
Can you explain why?

**Comment by robertsLando** [comment]
I have ioredis installed as a dep in my application

I'm actually overriding bullJs `createClient` function and If I return an ioreds 5+ instance the types are not compatible with 4

**Comment by manast** [comment]
Yes, but ioredis 5 is actually a very big change, v4 is stable and upgrading it will probably just introduce new issues...

**Comment by robertsLando** [comment]
I understand this, will wait for it so :)

**Comment by favna** [comment]
"probably just introduce new issues"

but will the ioredis v5 bump be done eventually or not? Right now I interpret your messages as it will never be done. That will deter me from using Bull extremely fast if that's the mentality of the maintainers.

**Comment by manast** [comment]
Maybe you are not aware we are putting most of our efforts in BullMQ: https://github.com/taskforcesh/bullmq

**Comment by chrismllr** [comment]
Unsure why this issue was closed, is the plan to halt development and put Bull into maintenance mode, in favor of BullMQ?

Applications may use other libraries in conjunction with Bull -- In our case, other packages within NestJS, which has a first-class Bull module. For example, the update to the latest version of the @nestjs/typeorm package is halted due to the fact typeorm@0.3.7 relies on ioredis v5.

**Comment by chrismllr** [comment]
@manast Found this MR, does this do the trick? https://github.com/OptimalBits/bull/pull/2398
