### ISSUE TITLE
Queue with multiple processors and rate limiter 

### ISSUE THREAD

**Issue by a-mitrovic-codefleet** [OptimalBits/bull#2394]
## Description
I have a problem when I define multiple processors and rate limiter for one queue. When I add for example 1000 jobs for one processor, all of them except first job which is completed immediately are going from waiting to delayed status, and only then start to processing even queue is empty. If I remove rate limiter, jobs are executed properly. Also, if I remove second processor, jobs are also executing properly. Am I doing something wrong?
## How to reproduce
```
const setUpUserTeamInfoQueue = new Queue('setting_up_user_team_info', {
    redis: '', // some config
    limiter: {
        max: 1,
        duration: 200
    }
});

setUpUserTeamInfoQueue.process(
    'set-up-user-team-info',
    `${__dirname}/../processors/set-up-user-team-info/set-up-user-team-info.processor.js`);

setUpUserTeamInfoQueue.process(
    'reset-today-user-team-info',
    `${__dirname}/../processors/set-up-user-team-info/reset-today-user-team-info.processor.js`);


const userIds = [4894, 9879, 7879, 789798, 77979, 77979, 7987, 798];

const jobs = userIds.map(userId => {
    return {
        name: 'set-up-user-team-info',
        data: { userId }
    };
});

await setUpUserTeamInfoQueue.addBulk(jobs);
```

## Bull version
4.8.3

**Comment by manast** [comment]
The rate limiter uses the delay functionality to delay rate limited jobs. Is the rate limiter not working or you are just worried that this is wrong?

**Comment by kulinsj** [comment]
I have a related issue with multiple processors and a rate limiter. My jobs are are executing significantly **faster** than the rate limit should allow, I'd greatly appreciate a bit of clarification. My setup is as follows:

I set up a queue with a rate limit of 24 tasks per 15 minutes, and I have 24 workers. I queue up 2,000 tasks to be slowly worked through over the next few weeks. The delay on the queued tasks is staggered, but still small, with the intention being that I want the rate limiter to control the execution speed. However, the queues are immediately processing _way_ more than 24 tasks per 15 minutes. I'm wondering if this line from the docs "Everytime the same queue is instantiated it tries to process all the old jobs that may exist from a previous unfinished session" could be the explanation, since after a few minutes, all 20k tasks are in the delayed state instead of the queued state. Would a server re-deploy for my workers which causes the queue constructor to be called potentially cause the queues to try to "catch up" while ignoring the rate limit? If so, would the bounceBack option on the rate limiter prevent this?
