### ISSUE TITLE
[Question] MaxRetriesPerRequest Error 

### ISSUE THREAD

**Issue by oreoluwa-bs** [OptimalBits/bull#2536]
## Description
The maxRetriesPerRequest error only during production, everything works fine on my local setup despite using the redis connection string (Upstash: tls turned off).

<img width="643" alt="Screenshot 2023-02-02 at 11 27 46" src="https://user-images.githubusercontent.com/46888096/216299988-3c5adae6-adeb-41b8-82cf-e07245aad0c8.png">

I found a solution to turn the maxRetriesPerRequest setting to null but then it just hangs indefinitely.

I would really like to know what i could be doing wrong. Thank you.

## Minimal, Working Test code to reproduce the issue.
```ts
import Redis from "ioredis";
import Queue from "bull";

const REDIS_URL = process.env.REDIS_URL as string;
const client = new Redis(REDIS_URL, {
  lazyConnect: true,
  enableReadyCheck: false,
  maxRetriesPerRequest: 3,
});
const subscriber = new Redis(REDIS_URL, {
  enableReadyCheck: false,
  maxRetriesPerRequest: null,
});

const redisOptions = {
  // redisOpts here will contain at least a property of
  // connectionName which will identify the queue based on its name
  createClient: function (type: string, redisOpts: any) {
    switch (type) {
      case "client":
        return client;
      case "subscriber":
        return subscriber;
      case "bclient":
        return new Redis(REDIS_URL, {
          ...redisOpts,
          enableReadyCheck: false,
          maxRetriesPerRequest: null,
        });
      default:
        throw new Error("Unexpected connection type: ", type);
    }
  },
};


 const queue = new Queue("queuer",redisOptions);


async function addToQueue(data) {
  const job = await queue.add(data);
  return job;
}


queue.process(async (job) => {
  console.log(job.data)
});
```

## Bull version
^4.10.2

## Additional information
Production environment
NextJS (custom server -> node runtime): "13.0.0", (Using the src directory)

Server environment
Centos 7 Cpanel

**Comment by manast** [comment]
There are basically two cases that should be treated differently. The first case is if you are a producer of jobs, if you are adding jobs to a queue then you would like to get an exception if the maximum number of retries has been exceeded, so just handle this error appropriately.  The second case is if you are a worker or consumer of jobs, in this case you will want to retry for ever, so that as soon as the connection with Redis is re-established you can continue consuming jobs without producing any error. 
This documentation even though is for BullMQ may be useful for this case: https://docs.bullmq.io/patterns/failing-fast-when-redis-is-down

**Comment by oreoluwa-bs** [comment]
Okay, Thanks I understand this.
A follow up question would be is there any reason it fails to connect to the redis instance especially in prod but doesn't fail in a local environment despite using the same connection values

**Comment by emanuelegorga** [comment]
@oreoluwa-bs I suspect that the issue is related to the TLS connection as Bull may be trying by default to use a "non-safe" connection and your Redis instance on production is expecting a TLS connection.

@manast can you help understand how Bull version 4 can be configured to use a TLS connection ? 🤔

**Comment by richardantao** [comment]
I'm having the same issues as OP. I tried setting the `enableOfflineQueue` flag, like so:

```
const queue = new Queue<T>(name, {
  redis: {
    host: REDIS_LABS_HOST,
    port: parseInt(REDIS_LABS_PORT),
    password: REDIS_LABS_PASSWORD,
    enableOfflineQueue: false
  }
});
```

But when I do so, I get the following error:
> node_modules/ioredis/built/Redis.js:358
> command.reject(new Error("Stream isn't writeable and enableOfflineQueue options is false")); 

I am on `bull^4.10.4`

**Comment by renrael-yzal** [comment]
```bash
BullModule.registerQueue({
      name: BullQueues.NOTIFICATIONS,
      createClient(
        type: 'client' | 'subscriber' | 'bclient',
        redisOpts?: RedisOptions,
      ): Redis | Cluster {
        return new Redis(config.REDIS_URL, {
          maxRetriesPerRequest: null,
          enableReadyCheck: false,
          showFriendlyErrorStack: true,
        });
      },
    });
    ```
    
    After passing redis client, instead of redis url or redis options, solved my issue.
