### ISSUE TITLE
Prefix option does not follow NodeRedis/node_redis

### ISSUE THREAD

**Issue by ht2** [OptimalBits/bull#305]
The README references the https://github.com/mranney/node_redis lib...

`redisOptions {Object} Options to pass to the redis client. https://github.com/mranney/node_redis`

...which now directs to [https://github.com/NodeRedis/node_redis](https://github.com/NodeRedis/node_redis).

However the prefix option in node_redis is simply `prefix`. Looking back to PR #177 (fixing issue #176), a `keyPrefix` option is now looked for.

**Comment by ht2** [comment]
Think I might have solved my own question, looks like use of `keyPrefix` is just a better option when using node_redis...

**Comment by tshelburne** [comment]
This hit me today, and took quite a while to figure out - is there any reason to use a custom configuration parameter name, particularly given that Bull explicitly suggests passing configuration that matches `node-redis`? It would be just as easy to use the `redisOptions.prefix` instead of `redisOptions.keyPrefix`, and accomplish all the same goals.

**Comment by manast** [comment]
I will close this since it has been properly resolved already and we are using ioredis now as well which changes how prefix is handled.
