### ISSUE TITLE
Listening to events from a non-worker?

### ISSUE THREAD

**Issue by haynzz** [OptimalBits/bull#389]
I was wondering if there was a way to "subscribe" to queue/job events from a process that has no worker running?

I have a Web-Server where the user can trigger an Update of a CSV-Data-file which takes a while. I have a worker running that executes that job. So I have two processes running:
- Server
- Worker

Both processes have access to a node Module `ExportApp` I created that actually is the component that knows about bull and everything. So the Worker only calls an `ExportApp.initProcess()` function. Within that function the `queue.process(handleStuff)` is called.

Now I want to be able to show changes on the Server-side (Socket or whatever) immediately to the user. A UI for the queue without knowing too much about redis and bull in the Server.
Is that a good approach and how would that be possible?

**Comment by manast** [comment]
normally you will have a bull queue acting as a receiver of the progress event or whatever. I usually also use the *Returning job completions* pattern as described in the README.

**Comment by haynzz** [comment]
Now that I read it it totally makes sense to communicate between processes via a queue.
But it still feels like overhead when I just want to observe - let's say - the currently active job's progress. 
Is there any realtime UI for bull queues that does not use redis directly to observe the queue?

**Comment by manast** [comment]
redis is being used for inter process communication, so no, you cannot do it without redis.

**Comment by doublerebel** [comment]
@haynzz It's possible to use node's native IPC to manually trigger events across processes, but in Bull there's no guarantee that the bull queue server and the workers are even on the same computer/instance.  That's why Bull keeps the job state in Redis.  Bull does use Disturbed module to listen to distributed events using Redis in the same manner as Node IPC, so you should be able to [receive these events from a process that has no worker running](https://github.com/OptimalBits/bull/blob/f1ea81c0e9a950f47d5aa39a2bc5ff82cb573355/lib/queue.js#L192).

Are you looking for just a UI, or do you also need to watch job events programmatically?  I'm writing docs for my UI today ( https://github.com/nextorigin/el-borracho-ui ) .  It's also easy to batch get the job progress with redis HGET, [here's the example in el-borracho](https://github.com/nextorigin/el-borracho/blob/master/src/redis-model.coffee#L327).

**Comment by haynzz** [comment]
@doublerebel Thanks for the suggestion. I now totally get why the Events that are emitted by the worker process itself do not reach any other process that tried to subscribe to them with `queue.on(...)`. 
But as I am thinking about it... I have a connection to the queue. Shouldn't it be observing changes there and emit events? I mean from the process that does not receive the events I am also able to `queue.add(job)`.
I know that this is probably not implemented in bull, but am I getting the concept wrong that this is not completely off to want bull to be able to also observe a queue for events without picking up jobs and locking them? (@manast)

To your other question. I want to be able to programmatically consume the events. In the end it's not for a full fledged queue-UI. It is just to disable an "update" button and show a loading indicator while an update-job is running.

And again. I want to avoid writing any code using a redis SDK myself (apart from the connection details.)

**Comment by manast** [comment]
The global events are quite new and I did not document them yet. Just listen to any event and add a true flag as third parameter:
```
queue.on('completed', listener, true);
```
