### ISSUE TITLE
[Discussion] Threads support

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#392]
I am considering the idea of adding support for threads in bull. The rationale is that we would avoid the problem where you have a heavy process function that holds the event loop too long time preventing the worker to update the LOCK and risking that another worker starts working on that same job.
I would like to start a discussion about pros/cons. At a basic level we could provide examples in the readme (which maybe is enough), or we may want to have a tighter integration, where threads could be optional, or maybe even always there, just transparent for the user.

So what do you think?

**Comment by bradvogel** [comment]
We use Fibers all throughout our codebase and even wrote a blog post about them: https://mixmax.com/blog/node-fibers-using-synchronize-js. The downside is that it's a very large native dependency, which could cause problems for some deployments.

I'd probably just make it a recommendation to wrap the worker callback in a new fiber (this is what do fwiw), as opposed to internalizing it in this project. There are other, perhaps better, strategies for ensuring the event loop isn't blocked like breaking up work into smaller chunks, spawning other processes, etc.

**Comment by wearhere** [comment]
@manast, I wonder if perhaps you are under the impression that fibers execute in parallel like threads. Unfortunately they do not—fiber B may start before fiber A completes, but only if A yields; they share the event loop. They're just an alternative to callbacks and promises for scheduling work on the loop.

So, if a heavy process function never yields, fiberizing it wouldn't help. And, the process function could be made to yield without using fibers—it could break its work up into a series of callbacks or promises, for instance.

Spawning processes, as @bradvogel mentions, _would_ enable true parallelism but would be harder to work with since processes don't share memory.

**Comment by manast** [comment]
You are right. I was confused thinking fibers where similar to webworkers. I found this other package instead: https://github.com/audreyt/node-webworker-threads

**Comment by manast** [comment]
This is already fixed in bull 3.x.
