### ISSUE TITLE
mixing getJobCountByTypes including paused yields 0

### ISSUE THREAD

**Issue by jamesjjk** [OptimalBits/bull#401]
We are in the process of replacing Kue with Bull and so far so good. However we noticed whilst implementing repeatable jobs that when we yield getJobCountsByType and include 'paused' the result yields 0 whilst there are delayed and active jobs present.

```
const count = yield _queue.getJobCountByTypes('paused', 'delayed', 'wait', 'active');
//RETURNS 0 (expected positive int)
```

```
const count = yield _queue.getJobCountByTypes('delayed', 'wait', 'active');
//RETURNS positive int
```

**Comment by manast** [comment]
hmm, when you are getting the count for paused jobs, is the queue actually paused?
Because when the queue is paused, it renames the wait queue so that the redis client that is processing jobs will pause the processing (globally), until the queue is resumed. So what I suspect it that getJobCountByType is not taking this fact into consideration, and returning 0 for wait when the queue is paused-

**Comment by jamesjjk** [comment]
@manast I didn't have the queue actually paused, and there were delayed, waiting, and active items available. However the count always returned 0 once I included paused literal.

**Comment by manast** [comment]
ok, I will write a unit test to see if I can reproduce it.

**Comment by GoNode5** [comment]
```javascript
QueueSend.getJobCountByTypes(['paused', 'delayed','failed']).then(function(result) {
  console.log('paused/delayed /failed jobcount:',result)	
})

QueueSend.getJobCountByTypes(['failed']).then(function(result) {
  console.log('jobcount:',result)	
})

QueueSend.getFailedCount().then(function (count) {
	console.log('failed count',count)
})
```
results in:
failed count 28
paused/delayed /failed jobcount: 0
jobcount: 28
