### ISSUE TITLE
Jobs with custom id and delay show as stuck

### ISSUE THREAD

**Issue by jamesjjk** [OptimalBits/bull#406]
It seems jobs with a custom id and delay get a stuck state, however the seem to work properly. Any ideas? Happy to test/pr.

**Comment by manast** [comment]
hmm, can you provide a test case?

**Comment by jamesjjk** [comment]
I have added various different jobs to a queue, some of these jobs I add a jobId as a custom unique string - which I can then use to atomically repeat the job at specific intervals (i.e. a delay). 

The problem seems to be that a delayed job with a custom jobId shows a stuck state (it does however repeat as intended). 

I checked the code and came across this, notably it does not check for customJobIds. Any ideas?

```
Job.prototype.isDelayed = function() {
  return this.queue.client
    .zrank(this.queue.toKey('delayed'), this.jobId).then(function(rank) {
      return rank !== null;
    });
};
```

**Comment by jamesjjk** [comment]
I realise its little todo with the isDelayed method, however simply adding a job with customId and delay should reproduce the problem.

**Comment by doublerebel** [comment]
The customJobId is turned into the jobId at job creation and does not survive past being an option.  It seems more this is related to #387 .  There are still some places that [plain jobId is returned as a number](https://github.com/OptimalBits/bull/commit/333d007f49571383cb682c71ffd6f208e8ee5b07#diff-6c5bd8371f6ad4b9acf7b619733429e2R100), the mismatch [broke some of my related tests too](https://travis-ci.org/nextorigin/el-borracho/jobs/178939113#L403).  I'm working on a PR for the underlying cause here.

**Comment by jamesjjk** [comment]
@doublerebel Great if there is any data I can provide, let me know.

**Comment by jamesjjk** [comment]
@doublerebel Did you manage to find the error with your test?

**Comment by manast** [comment]
I think this issue is not reproducible on 3.0.0 branch so I will close it for now.
