### ISSUE TITLE
 fatal queue

### ISSUE THREAD

**Issue by GoNode5** [OptimalBits/bull#423]
I would propose a fatal queue, for permanent failures where jobs are moved after x attempts and delays.
Failed is more a retry/delay function. Not sure you could set the max attempts per queue. 0 attempt could mean move directly to fatal, after failure (done(Error())

**Comment by bradvogel** [comment]
`Failed` is already the permanent failure queue. Delayed jobs wait in the `delayed` queue.

**Comment by manast** [comment]
@GoNode5 why did you belive that retried jobs were stored temporarily in the failed queue?

**Comment by GoNode5** [comment]
To reschedule a job, it first have to be in the failed queue. I'am sending outbound mails. Sometimes mail has a wrong structure, so there is no point of 'auto' reschedule I do reQueue(all failed jobs). But I don't want to lose any message whatsoever. (done(Error(),fatal) could move the job to a permanent failed that needs manual attention.

**Comment by bradvogel** [comment]
So are you waiting for email job to fail, then examining the reason why (eg wrong structure), modifying the job data to fix the structure, and then reenqueuing? If so, how about using the `backoff` parameter to let Bull auto-retry it, and before a job fails, edit the job data and save?

**Comment by GoNode5** [comment]
With email > 99% its a internet failure (no internet/service not reachable/dns). So auto retry/delay is in order with failed/retry. It will be send out. In a special case internet is down for hours (happens once a year), all the failed jobs should be resend again... no problem. 
1% is wrong by structure/json somehow. These need manual attention, no point to reschedule auto retry etc... But they stay in the failed queue. On the end the failed queue should be empty.
Could I otherwise move this job to another queue?

**Comment by bradvogel** [comment]
If I were you, I'd use Bull's exponential backoff feature so the emails retry over many hours. But if you can distinguish a "wrong structure" failure from an "internet connection" failure in code, you can prevent "wrong structure" from retrying by calling `job.markUnrecoverable()` (when https://github.com/OptimalBits/bull/pull/418 merged), and you should also `throw new Error('invalid format')` to mark the job. Then the all jobs in the `failed` queue will be either due to internet connection issues (but have already been retried for X hours), or jobs with the `invalid format` in their error stacktrace. Then you can manually go through the failed queue and determine what to do with each job.

**Comment by GoNode5** [comment]
By job.markUnrecoverable() you already show that there can be 'special' jobs in failed. These jobs should not stay in the failed queue in my view...  But I don't seem to convince so let's carry on. Thank for your time and comments

**Comment by manast** [comment]
What about creating a different queue for handling these jobs? Just remove it from the main queue and create it in the other queue. You will loos atomicity, but maybe thats ok. If the case becomes very common we could have a special atomic method ```moveToQueue``` that atomically does this for you.

**Comment by GoNode5** [comment]
@manast I prefer 1q but I'll go that way yes thanks. MoveToQueue would be great to.
