### ISSUE TITLE
Check for lock existence in the scripts where it makes sense

### ISSUE THREAD

**Issue by manast** [OptimalBits/bull#498]
such as:
- moveToDelayed.
- takeLock.
etc

**Comment by manast** [comment]
I think I going to keep this issue on hold. It is not completely trivial to understand where we actually need to defensive check if a job is locked.

**Comment by bradvogel** [comment]
I think the only other places that need to check for a lock are the `moveToDelayed` and `retryJob`scripts (`moveToFinished` and `moveToCompleted` already check the lock).

The scenario I'm thinking of is:

| Time | Process A | Process B |
| --- | --- | --- |
| 1 | In the regular Bull run loop of Process A, job 1 is being processed. The event loop happens to stall. |  |
| 2 |  | In Process B, the job gets picked up as a stalled job and lock is taken. |
| 3 | Event loop unstuck. Fails to renew the lock (because Process B has it), but that doesn't stop processing (due to [this](https://github.com/OptimalBits/bull/blob/v3.0.0/lib/queue.js#L752)). Job happens to fail and is moved to the delayed state [here](https://github.com/OptimalBits/bull/blob/v3.0.0/lib/job.js#L171).  | |
| 4 |  | Process B finishes processing and the job completes. But it's already in the delayed state! |

If the lock was checked in `moveToDelayed` it would have not touched the job and let Process B continue with it.

**Comment by bradvogel** [comment]
I tried the above manually and it results in the dreaded `Unexpected token u in JSON at position` error because the job is moved by a worker without the lock.

**Comment by bradvogel** [comment]
I tried to fix this but ran into an issue that I need your help on. It looks like `ARGV[3] timestamp` is never passed in to the moveToDelayed script here: https://github.com/OptimalBits/bull/blob/v3.0.0/lib/commands/moveToDelayed-3.lua#L11

Could this be causing problems currently?

I was trying to add the following to the moveToDelayed and retryJob redis scripts:
```
  if ARGV[4] ~= "0" then
    local lockKey = KEYS[3] .. ':lock'
    if redis.call("GET", lockKey) ~= ARGV[4] then
      return -2
    end
  end
```

**Comment by bradvogel** [comment]
Also - it'd be nice to pull this back into 3.0.0 milestone since it's the last remaining non-atomic codepath that can result in corrupted jobs.

**Comment by manast** [comment]
I am actually a bit confused myself, what is the use of ARGV[3] anyways? It does not seem to be used for anything. I will investigate more...

**Comment by manast** [comment]
yeah, it seems like old code coming from a more generic move function. I must have copy pasted that code wrongly, will fix it ASAP and add the lock check:
https://github.com/OptimalBits/bull/blob/master/lib/scripts.js#L693-L698

**Comment by manast** [comment]
https://github.com/OptimalBits/bull/pull/539
Still, we do not have a proper test case that triggers the issue that you were able to reproduce earlier. Is it tricky to make it into a mocha test ?

**Comment by bradvogel** [comment]
You're right - let me see if I can come up with a test case

**Comment by bradvogel** [comment]
Added a few test cases to https://github.com/OptimalBits/bull/pull/539#issuecomment-302980212. These cover my scenario where a second processor is trying to work on a job while it's being moved.
