### ISSUE TITLE
More lightweight queue clients.

### ISSUE THREAD

**Issue by richburdon** [OptimalBits/bull#526]
I have a job processor running in one container -- and a CLI and web server both of which adds jobs.

The model seems to be that all processes that create Queues become workers (i.e., the node process doesn't return). What's the approach to build something that is client-only?

**Comment by manast** [comment]
hmm. A worker, in bull terms, is by definition a queue that specifies a ```process```. However, when you instantiate a queue several listeners and timers are setup, so you need to properly call queue.close(), so that everything is cleaned up and the process can exit. Please let me know if this resolves your issue.

**Comment by richburdon** [comment]
I have many different processes (in different containers) that only add
jobs and a different processor that consumes them.

It seems extremely expensive for a "client" to have to set up a worker just
to add a job then tear it down? Eg rather than a simple api to add jobs to
the queue.

Examples:
- a webhook in my web server adds a job to the app server.
- admin cli add jobs from command line input

**Comment by manast** [comment]
After some more thinking I am a bit confused about what this issue is all about. A queue, working as a client or as a worker, requires always 2 connections (In bull 3.x). One for listening to events and the other to add jobs or process jobs, etc. When you are done with the queue, being a client or worker, you should call ```close``` to avoid leaking resources. So what is extremely expensive in this approach, and how could it be done better?

**Comment by richburdon** [comment]
Hi Manuel, sorry the "expensive" comment may be due to a misunderstanding
on my part; I potentially have lots of "clients" that only submit jobs, so
I was worried about the Redis server having lots of open connections. So to
be clear, my use case is for clients that only post jobs -- never listen
for events (e.g., webhooks on frontend servers). So they only require one
connection. I think to support this you could have an option { worker }
that is true by default, but when false prohibits binding processes or
listening for events (e.g., the seemingly defunct bee-queue project
supports this option).

Anyway thanks for this package.

**Comment by manast** [comment]
My plan is to set the listeners only if a) a process function is defined, b) an event listener is defined. 
This way it will use the minimum amount of clients automatically without any extra options.

**Comment by marshall007** [comment]
I have a PR up for this in #586. My use case was similar. I needed to query for active Queues and their job counts to expose them in a REST API and wanted to reduce the number of connections and calls to redis to a bare minimum.
