### ISSUE TITLE
Stopping/Pausing repeating jobs

### ISSUE THREAD

**Issue by ambirex** [OptimalBits/bull#582]
If I am reading [this line](https://github.com/OptimalBits/bull/blob/45e0c5c95f6b8cce82b7de0917884b7c5607123a/lib/queue.js#L928) correctly, Bull issues a new job on returning the next job in the queue. I believe this gets a new job id so I can't reference the original job to cancel it.

I don't see a current way to stop, pause or delete a repeating job. Am I missing something? How do you change a current repeating job?

**Comment by ambirex** [comment]
I just found #558 (sorry, I must of overlooked it when searching) which seems to be related to this question. I'm not sure if this technically a duplicate but we seems to be asking close to the same question.

**Comment by manast** [comment]
@ambirex repeating jobs is a new functionality and there perhaps we need to add more functions to it. Currently you can specify a endDate so that the repeating job does not continue repeating after that date. I have not tested it yet, but I think that if you add the same repeat job with a endDate that is older than the current date you would effectively cancel the job.

**Comment by andrewburgess** [comment]
@ambirex With the patch I submitted, calling `queue.add` will always return the next job iteration now. It should be possible to call that to get a reference to the job and then call `remove()` on it to stop/delete the job if the `endDate` method doesn't work for you.

**Comment by ambirex** [comment]
@andrewburgess that sounds workable I'll try it out once it is available in a release, thank you.

@manast the `endDate` is certainly a possibility, I'm curious on what were the use cases you were looking at for repeating jobs. Because all of mine uses center around the idea of having the repeating jobs be unique.

For example: I need a job that will access an API and issue jobs on the results. I really want that job to be unique, so I don't try and reprocess the same result twice. All of my own use cases follow this pattern. From my perspective, I am interesting in having an addressable repeating job in a queue that is guaranteed to be unique. @andrewburgess's solution allows for this but it does seems a little awkward to only have access to the job after an additional `queue.add`.

**Comment by manast** [comment]
@ambirex  the fix from @andrewburgess is already in the latest version (rc3).
Regarding use case for repeat, for example a job that does garbage collection in a database once a day, or that perform payments for users subscriptions. This are typical jobs that run forever.
Maybe what we need is so simple as a method to fetch a repeat job so that it can be removed.

**Comment by ambirex** [comment]
@manast I just tried rc3 and I was indeed able to remove the job.

It does seems a little awkward to only be able to access it after `queue.add`, but it is workable. More function's ability to address the existing jobs would be welcomed.
