### ISSUE TITLE
Event chaining no longer works

### ISSUE THREAD

**Issue by ferronrsmith** [OptimalBits/bull#608]
version :  `3.0.0-rc4`

```javascript
taskQueue.on('ready', () => {
  // Queue ready for job
  // All Redis connections are done
  logger.trace('Task Queue is now ready');
}).on('error', (error) => {
  logger.error(error);
}).on('active', (job) => {
  logTask(job, 'Started');
}).on('stalled', (job) => {
  // Job that was considered stalled. Useful for debugging job workers that crash or pause the event loop.
  logger.trace('job stalled', job);
}).on('completed', (job) => {
  // Job completed with output result!
  logTask(job, 'Completed');
});
```

Errors

```javascript
/bull-queue/worker.js:39
}).on('error', (job) => {
   ^

TypeError: taskQueue.on(...).on is not a function
    at Object.<anonymous> (/bull-queue/worker.js:39:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

```

**Comment by manast** [comment]
Yes, this is because .on now returns a promise, since we lazily subscribe to redis events for less overhead on the clients that do not need to listen to events. A possible fix could be that I put a .on method in the promise that allows you to continue chaining events as you do now, the only drawback is that it will only start listening after the previous event has been completely registered, but I guess this is a negligible problem.

**Comment by marshall007** [comment]
@manast I think it would make sense to just continue returning `this` from event emitter methods. I can't think of a use-case where you'd really care to know _when_ the event was finally subscribed to. Just because the queue is attaching handlers asynchronously doesn't mean the user needs to be made aware of that fact.

**Comment by manast** [comment]
@marshall007 there is an important use case, and that is in the unit tests. Many of them need to know when the listener is active... if we can solve that in some other way then it is ok to return this as before.

**Comment by marshall007** [comment]
@manast perhaps emit an `__handler` event each time an event listener is successfully attached? Then we could do `queue.once('__handler')` as a promise replacement in the unit tests?

**Comment by manast** [comment]
@marshall007 interesting idea. I will think more about it.

**Comment by marshall007** [comment]
@manast sounds good. The new behavior is pretty bad since it's not only a breaking change, but also breaks user expectations as `EventEmitter`-based APIs are generally always chainable. I think we're going to have to fix this one way or another.
