### ISSUE TITLE
How do jobs end up on the paused list?

### ISSUE THREAD

**Issue by albertjan** [OptimalBits/bull#65]
I was reading through the code and I can't find where jobs are getting pushed onto the paused queue.

I ran into this because I don't understand why you return the length of the longest list in `Queue#count`

```js
Queue.prototype.count = function(){
  var multi = this.multi();
  multi.llen(this.toKey('wait'));
  multi.llen(this.toKey('paused'));

  return multi.execAsync().then(function(res){
    return Math.max.apply(Math, res);
  });
}
```

I'd expect this to be the `length of paused` + `the length of wait`. But since its unclear to me how jobs end up on the wait list. I thought I'd just ask.

**Comment by manast** [comment]
A job that is paused has been moved from wait to paused, so therefore in order to count all the jobs that remain to be processed we need to add both lengths

**Comment by albertjan** [comment]
Allright so `return Math.max.apply(Math, res);` should be `_.reduce(res, function (a,b) { return a+b; })`

**Comment by manast** [comment]
wait a sec because I think I am totally wrong here...

**Comment by manast** [comment]
The problem is that the pause implementation is not really finished, if you read the comment on top of the pause method you may understand it better. 
The pause functionality is just local for the queue instance were you call pause, so there are no redis queues affected and such. Also the pause is for the whole queue not for jobs.
The planned implementation of pause is like this:
pause -> rename redis wait list (incoming jobs) to paused
if new jobs are added while paused, add them to paused instead of wait.
resume -> rename redis paused list to wait
after renaming back to wait, the connection that is blocked waiting for new jobs will start returning jobs.
This means that in fact the current code for count is correct when the real implementation is done (i.e., taking the max of wait and paused (one will be zero the other will have all the items). But since we hace delayed jobs now, we also need to add the count of the delayed set.

**Comment by manast** [comment]
I think I can find some time today to finish the pause functionality. It will be great because it will pause the queue globally independent on how many clients or workers are using it.

**Comment by manast** [comment]
This has been fixed here https://github.com/OptimalBits/bull/commit/4e8421e5b86ac4af988c8e6b650ec7638ff5566c
