### ISSUE TITLE
Delayed jobs

### ISSUE THREAD

**Issue by richthegeek** [OptimalBits/bull#7]
It's occasionally a requirement for a job to not be done for at least N seconds.

There are two obvious API methods for doing this:
1. Addition of "delay" to the job options accepted by Queue.add / Job.create
2. Addition of a "delay" method to the Job class

(For Kue, the second option makes sense because Job objects can be used from within their own processor, so failed jobs can have a delay before retrying. With Bull it doesn't make much sense, i think?)

How to implement this? Essentially, delayed jobs are put into a ZSET with the score being the time that they should be processed after. Then, the system polls ZRANGEBYSCORE (once Queue.process is called, or once Queue.processDelayed() or something like that is called) from 0 to now, and puts those jobs onto the active queue as before.

If you want me to hammer out a PR once we have discussed the API choices a bit then I'd be happy to - something with a bit more care than Kue would be great!

Of course, it might also be a nice distinct library / extension for bull that can be added distinctly.

**Comment by gyril** [comment]
@manast still no update on this? do you have an idea of what the API will look like eventually? I'm working on something similar and might as well help you get there

**Comment by manast** [comment]
I am working on this feature right now, it should be ready in a couple of days. It is based on a separated sorted set and some logic to schedule when the delayed jobs must be processed.

**Comment by manast** [comment]
WIP: https://github.com/OptimalBits/bull/tree/delayed

**Comment by manast** [comment]
The version in the delayed branch is now functional, although it lacks some improvements like atomize some functions as well as handle delayed jobs when using multiple workers. Other than that I am quite happy with the design so far, since it still does not need any polling, just a cheap client side timer that is only called once per delayed job. Great if you guy could check the code and/or test it more.

**Comment by manast** [comment]
I have made a new update, now delayed jobs should also work for multiple workers. Only missing thing before it can be merged into master would be to atomize the updateDelayTimer method.

**Comment by manast** [comment]
https://github.com/OptimalBits/bull/compare/delayed?expand=1

**Comment by albertjan** [comment]
https://github.com/OptimalBits/bull/compare/delayed#diff-d823dceb04482ab55e5004eebb53fc1cR126 

This line should probably be: `var _this = this;`

Isn't there also a possible race condition in `processJob` the `publish` and the `moveToDelay` aren't always guaranteed to happen both. Two instances of bull might both reach `moveToDelay` at the same time.

**Comment by manast** [comment]
I have updated the implementation with an atomic updateDelayTimer, now it should be feature complete and could be merged into master if no bugs are found.

**Comment by manast** [comment]
@albertjan what you are saying is correct, regarding publish and moveToDelay not executed atomically. This could be also implemented as a redis lua script to guarantee that both are indeed executed. I will take a look into it. 
Regarding two clients calling moveToDelay at the same time it should not be possible since when we reach processJob the job as atomically been moved from wait to active and no other worker should be able to process the same job.

**Comment by manast** [comment]
ok, done. I have now atomized the publishing and moving to the delay set.

**Comment by manast** [comment]
This issue is now completed, merged on master and released in bull-0.2.0. I would like to thank @richthegeek for his insights and ideas, the current solution is very similar to its initial proposal, although based on a poll-free design.

**Comment by toddbluhm** [comment]
Sweet! Thank you so much @manast
