### ISSUE TITLE
How to choose Named processor or Individual queues?

### ISSUE THREAD

**Issue by Unibozu** [OptimalBits/bull#724]
Hi,

I've been implementing Bull using individual queues for each kind of Job. What's your take on choosing either named processor or individual queues? Are there performance-related elements I need to consider? If yes, how would they influence the decision? Just so you know I am looking at building a production-ready job processing, so I need to make a decision that will scale properly in the future.

In any case, I have an abstraction in place that will make it easy to migrate between one or another, but it'd be good to have some hints to help my original decision.

Also, sharing `ioredis` client between queues is really cool, you may want to warn that if there are more than 10 queues using a single client, `ioredis` EventEmitter need to be tweaked using `client.setMaxListeners(50);` to avoid process warnings (I believe the default is 10).

Thanks

**Comment by manast** [comment]
Named processors are just a small convenient feature in the case you may have a queue with similar jobs, instead of having a switch-case you can use the named jobs to separate the code.
Having separate queues adds more flexibility, for example you can scale with a different amount of workers per queue, and also have the jobs work better in parallel, since one job type that may be very slow will not affect the performance of other jobs, etc.

**Comment by Unibozu** [comment]
That makes sense and it felt like the right way to do. Thanks
