### ISSUE TITLE
[Question] Unit tests against jobs

### ISSUE THREAD

**Issue by zeluis9** [OptimalBits/bull#729]
I'm currently looking for some sort of _guideline_ on how should I write some tests for my jobs. Although they're working as intended right now, I don't know how can I properly test them to ensure that nothing is broken due to a hipothetic change to the codebase in the future.

**Comment by AlmightyBaka** [comment]
I had this problem too. Indeed, it's a pain to test because you can't really return any value from a job once it finishes. You can add/check some side-effects (like a global variable or, if your job is writing to a db, get the result from it and see if it's what you expect it to be), but obviously that's not nice at all.

If you're willing to move to a different framework because of this, I would advise you to check out [Comedy](https://github.com/untu/comedy). It's an actor framework for Node, and so far I reeeeally love it 😍 It can do all the same things a queue like Bull can do, plus has lots and lots of other features like easier scaling, allows for way better code quality and, most importantly, can have a return value from an enqueued method 😂

**Comment by manast** [comment]
@AlmightyBaka it is not a pain at all to test. You can just run your process function isolated in any unit test framework you want, it is pretty simple, really.
On the other hand is quite lame to come here to promote a different library that has nothing to do with job processing and certainly cannot do the same things but better.
