### ISSUE TITLE
Single-process concurrent processing

### ISSUE THREAD

**Issue by LewisJEllis** [OptimalBits/bull#74]
I'm currently using kue in a project but really like the looks of bull - much simpler, great testing, and the recently-added timeout option fits a use case I have really well. 

The main feature of `kue` that's keeping me from switching is the ability to process jobs concurrently within a single node process (i.e. without `cluster`):
https://github.com/LearnBoost/kue#processing-concurrency
https://github.com/LearnBoost/kue#parallel-processing-with-cluster

This is particularly useful when jobs are mostly just waiting around on network/DB responses. It feels like something that should be a first-class citizen in the `queue.process` API. Any thoughts on whether this can be implemented? It seems a little tricky since queue processing is oriented around one job via a simple promise pipeline, but I'd be happy to take a shot at it with some guidance.

**Comment by manast** [comment]
Hello,

in order to keep the module simple, cluster support is not built in, but as you can see in the README is quite simple to implement it:
```
var
  Queue = require('bull'),
  cluster = require('cluster');

var numWorkers = 8;
var queue = Queue("test concurrent queue", 6379, '127.0.0.1');

if(cluster.isMaster){
  for (var i = 0; i < numWorkers; i++) {
    cluster.fork();
  }

  cluster.on('online', function(worker) {
    // Lets create a few jobs for the queue workers
    for(var i=0; i<500; i++){
      queue.add({foo: 'bar'});
    };
  });

  cluster.on('exit', function(worker, code, signal) {
    console.log('worker ' + worker.process.pid + ' died');
  });
}else{
  queue.process(function(job, jobDone){
    console.log("Job done by worker", cluster.worker.id, job.jobId);
    jobDone();
  });
}
```

**Comment by LewisJEllis** [comment]
Yes, I understand that, but cluster involves multiple processes; I want to have concurrent job processing in one process. My jobs do a lot of waiting for db/network requests to come back, so it doesn't make sense to have an entire process for each one; it's the nginx vs apache paradigm.

**Comment by manast** [comment]
ah ok, I understand what you mean. That would be as easy as making several instances of the same Queue name in one .js file. :).

**Comment by LewisJEllis** [comment]
Ah, I see; I had considered invoking `queue.process(...)` multiple times, but ruled that out. Multiple instances of the same name will work fine, though.

Thanks!

**Comment by LewisJEllis** [comment]
Actually, on second thought - that's going to create a lot of superfluous redis connections; if I want to process 20 at a time, I'll be creating 40 redis connections, which is rather wasteful.

**Comment by manast** [comment]
I don't think those connections incur in a great waste but sure they are not totally for free.

**Comment by seriousben** [comment]
@LewisJEllis Have you had luck running `queue.process(...)` multiple times?

**Comment by LewisJEllis** [comment]
@seriousben no; in order to ensure that the handler function isn't changed after processing starts, calling `process` more than once will throw an error.

**Comment by lchenay** [comment]
Creating as many queue as you want seems to work well.

```
function process(name, concurrency, fn) {
    while (concurrency--) {
        var q = Queue(name, hostname, post);
        q.process(fn);
    }
};
```

**Comment by manast** [comment]
I have given more thought about this, and also it seems as if the number of connections is in fact an a show stopper issue for some users, so I plan to implement threads so that a worker can in fact process several jobs in parallel. I will use this module unless somebody else have a better suggestion:
https://www.npmjs.com/package/webworker-threads

**Comment by lchenay** [comment]
Why using thread? Nodejs are event based, that work well. (quote: "it's the nginx vs apache paradigm" @LewisJEllis )

How thread will reduce connection ? If thread share same connection, it will make many edge case like : if a thread close connection, what happen to all other that use the same connection?

Thread will produce many overhead : it will duplicate memory of all lib. It will use all CPU even if user don't want to (and if it does, user should better use a cluster system).


Currently what is the main problem to reuse connection between Queue? What is the bottleneck?

I have tested a code like this in production:
```
Queue.processConcurrent = function(name, concurrency, handler) {
    this.handler = handler;

    while (concurrency--) {
        q.run();
    }
};
```

Execute run() several time on a queue, produce concurrency as wanted, reuse connection and works very well.
Some problem can appear like: 
- if queue restart, it restart only with a concurrency of one
- if stalled job, error can appear because concurrent will try to process them at the same time

**Comment by manast** [comment]
@lchenay I think I have not explained properly what I wanted the threads for. The idea is similar to your code ```processConcurrent```. Instead of running the handler in the same context as the queue itself, it will run on a separate thread. There are a few advantages with this:
1) The handler can be "aborted" (just killing the thread for example, or some other mechanism).
2) A handler that crash or enters a infinite loop will not hang the whole queue.
3) If multicore, several CPUs will be reused (as with the cluster example but with less connections to redis)
4) No extra connections required to redis.

**Comment by manast** [comment]
btw, in your example code, you call run several times which will end in calling ```brpoplpushAsync``` several times as well. I am a bit surprised that this works, I thought that calling ```brpoplpushAsync``` would block that connection and that it could not be used for anything else. Are you sure this works as expected?

**Comment by lchenay** [comment]
Yes brpoplpushAsync is blocking and it's the wanted behavior.
It's blocking only if they have no job to process. This connection is only used to get new job.

**Comment by lchenay** [comment]
For thread, we should be careful. module and user code could not work as expected within thread. It's not a common pattern in node world.

**Comment by manast** [comment]
regarding ```brpoplpushAsync```, what happens when you call it more than once with the same connection as it is the case with:
```
while (concurrency--) {
        q.run();
    }
```
?

**Comment by manast** [comment]
regarding threads. The main problem with threads as you say is that the thread will not share any context with the main module, which in fact would imply other complexities. The other alternative is to run several jobs in the same module but then it is very important that every job works iteratively otherwise no concurrency is achieved: the jobs will be just queued in memory instead of redis...

**Comment by lchenay** [comment]
It works just well :-).
I will make behavior test and PR when I finish other work.

**Comment by manast** [comment]
I will close this since it is now fixed on the current released version.
