### ISSUE TITLE
Linter rules?

### ISSUE THREAD

**Issue by leontastic** [OptimalBits/bull#756]
I'd love to continue contributing to bull in the future, but it would be nice to have a more complete set of linter rules to enforce consistency. What are your thoughts about adopting a widely-used eslint config like [Airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) or [Standard](https://github.com/feross/eslint-config-standard)?

PS @manast You do a great job of maintaining this project.

**Comment by weeco** [comment]
I was absolutely missing it as well. I also saw that the code style is not consistent across the library. Personally I also like the Airbnb rules.

Actually I was about to create an issue with a couple ideas how to improve the whole project.

It seems to be brash to suggest that, but I think converting the project to TypeScript would help the project in many ways. It helps coding, you can automatically extract the TypeScript definitions (and they are always up to date hereby), it helps for the documentation where Manuel seems to prefer Typescript definitions too.

**Comment by leontastic** [comment]
I would love to adopt syntax features from more recent Node.js versions too, such as arrow functions and `const` keyword. Would make the code much more concise.

**Comment by weeco** [comment]
@manast Can you provide some feedback? It wouldn't be much work to add that, but probably nor @leontastic or someone else would like to do a pullrequest for something we haven't agreed upon?

**Comment by manast** [comment]
we have a lint task in gulp, so we have at least some kind of linting. I did not have time to check the airbnb rules to see if they would work well with current database. In any case, as long as we run javascript we need to support at least version 0.4 of nodejs, so we cannot use the latest features. Going the typescript path would mostly require a major release, so that we can take advantage of typescript features. One thing I do not like of typescript though is that classes (unlike interfaces) are not open ended, so we cannot modularise in a aspect oriented way as we have today (separate files for repeatable, workers, getters, etc).

**Comment by mxstbr** [comment]
Picking this back up, we've (very successfully) introduced [prettier](https://github.com/prettier/prettier) to both `styled-components` and `react-boilerplate`, and I know of a ton of other open source projects that use it too.

The way most folks set it up is as a pre-commit hook with `lint-staged`: Whenever a contributor commits, their changes automatically get formatted by `prettier` to the common style. They can type the code in whatever style they prefer, but the main git tree is always consistent.

I'd be happy to submit a PR for adding prettier!

**Comment by manast** [comment]
Maybe, I would like to first see how much does it affect the current codebase. Can it be configured so that it follows as much as possible the current style?

**Comment by manast** [comment]
ah ok, there is a PR already ;)
