### ISSUE TITLE
Timers not always being cleared when closing, causes hanging process

### ISSUE THREAD

**Issue by jeffijoe** [OptimalBits/bull#806]
I'm run into a weird issue with closing the queue.

When calling `queue.close()`, it seems the timeout created by https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L803 is not cleared (even though I can see in the code that it should be). I found this using [`wtfnode`](https://github.com/myndzi/wtfnode) as my Jest process would not exit.

Commenting out line 803 that creates the timer makes it work as expected.

Additionally, doing

```js
queue.close().then(() => queue._clearTimers())
```

also fixes the issue. Perhaps running it again at the end of `close` might be a good idea?

**Comment by holm** [comment]
We are seeing a similar situation. On a SIGINT we call queue.close() and wait up to 10 seconds for the queue to shutdown. However it seems in many cases that never resolves, so we end up always waiting the full 10 seconds and then killing the process.

I cannot easily reproduce the problem locally, since it since to happen after some time running.

**Comment by gabegorelick** [comment]
I think the issue is that `startMoveUnlockedJobsToWait()` may be called *after* `close()`:

```js
Queue.prototype.run = function(concurrency){
  var promises = [];
  var _this = this;

  return this.moveUnlockedJobsToWait().then(function(){
    // this may execute after queue.close() has been called
    while(concurrency--){
      promises.push(new Promise(function(resolve){
        _this.processJobs(concurrency, resolve);
      }));
    }

    // this registers a new timer
    _this.startMoveUnlockedJobsToWait();

    return Promise.all(promises);
  });
};
```

**Comment by xfg** [comment]
I faced to this problem too. Can I use the workaround `queue.close().then(() => queue._clearTimers())` safely at production ?

**Comment by holm** [comment]
This is pretty problematic for us, as we are waiting for the queue to shutdown properly. We have added a timeout for this, but it makes our deployment be much more disruptive, as it waits for a while for the old process to complete, before we start a new one.

I don't understand how the workaround with clearTimers could work, since it is only called after close has resolved.

**Comment by manast** [comment]
@holm It is a bit late today, but I can make a new release tomorrow with the PR above, no guarantees that it will solve the issue but it was definitively wrong before so there is a chance it is the cause of it.

**Comment by manast** [comment]
@holm did you have a chance to test if the new release resolves the problem?

**Comment by holm** [comment]
I tested it just now, and from what I can tell it does fix the issue.

Thanks a lot!
