### ISSUE TITLE
How could I disallow duplicated task creating?

### ISSUE THREAD

**Issue by ks-s-a** [OptimalBits/bull#855]
There are tasks with data by id refreshing.

I would like to set such tasks in queue only if there are not the same tasks with the same id. Tried to use custom jobId, but can't use it if I don't clean a completed task - this id has already existed.

Is there any solution for that?

**Comment by manast** [comment]
Not sure I understand you use case. Custom Ids works so that if a job with a given ID has been added, new jobs added with the same id will be ignored. Is this not what you want?

**Comment by ritter** [comment]
Chiming in here with my particular case because I think it's similar. I have to get the job by its custom jobId and get it's state.  For 'failed' or 'stalled' jobs I want them to be re-added not ignored.  I currently have to manually remove them before adding them again.

**Comment by ks-s-a** [comment]
@ritter you can add handlers for corresponded events and just remove such tasks:

`
queue.on('failed', function(job, result) {
  console.log(`Job ${job.id} failed! Result: ${result}`);
  job.remove();
});
`

**Comment by ritter** [comment]
I could use: removeOnFailed too, but I wanted changes to examine the job first.  However, when trying to re-add the job, I don't want past failures to prevent it from being added.

**Comment by ks-s-a** [comment]
@manast mb you could give an advice for our cases?

**Comment by manast** [comment]
@ks-s-a ritter's method seems to be a good on for this use case. Of course, deleting jobs by hand always incur in a risk of not succeed and then having a zombie job... but maybe it is an acceptable risk in your case.

**Comment by ks-s-a** [comment]
@manast but for the my case I don't want to delete finished jobs. It could be important for debugging.

**Comment by manast** [comment]
you could copy the data to some other place and then delete them...

**Comment by cendrizzi** [comment]
I'm looking at something similar to this too. I want to be able to have a unique job and have it run, and ensure there are no duplicates added. For me there are several jobs like this in a specific queue that will be re-run many times over. 

At first I tried tacking this in the handler of the job. Essentially putting in a lock using redis that says if this job id is locked then just ignore it and finish the handler right then. But locks like this are problematic and it felt like a hack adding this in a handler.

Then I saw jobId. This is nearly ideal, except if you want to retain completed and failed for logging purposes then you can't use the same job id.

So I'm in the same place as many of you are. Copying data would be possible but unfortunate since I already have things in place to pay attention to the completed and failed queues. If I could change the job id on complete or fail to something else then that would be fine, almost like the job taking on a special archive id, but this might have other issues I'm not thinking on.

My other thought is at the time of adding a job id, I could use an increment redis key and add that to the end of the job id. Before adding I could checking what the status of the current increment appended value is and if it's completed or failed then I would INC the redis value and add a new job with this new value. This would likely be a big hit on the performance of Bull since I don't know how to do it without use job.getState() but it might be okay for my use (I already regularly clean my bull queues anyway since they would get too big to be useful with all my finished jobs, I just want a couple of days worth just in case I want to troubleshoot something)

I noticed that when you get the results of an queue.add there is no way to see from the results if that key already exists and therefore will be ignored. Is this really the case or am I missing something?

**Comment by ks-s-a** [comment]
@manast 

We all (and many developers which are not following this issue) want to obtain the key-like option for waiting queue checking only without any magic with task data moving (which looks really weird).

You are the boss here, please, let's discuss the feature in the thread.

**Comment by manast** [comment]
I wish there was a simple solution for this usecase. Currently jobs are uniquely defined by their Ids, it is not possible to have 2 different jobs with the same id, regardless of the state they are in. What we would need is some other type of Id, maybe a job "type", where you could only have one job type in the waiting list at the time. It is still not a super simple implementation but could be done.

**Comment by lxcid** [comment]
I have a slightly different problem though. What if I want to mimick a debounce effect, conditionally push back the job further if needed be.

I think removing/adding back the job with the same ID outside the processor might have a small chance of race condition?

Another solution is to do these inside the processor? But I can’t retry with a delay with `Job.retry`, so I might have to discard/requeue, but that seems wrong.

**Comment by manast** [comment]
@cendrizzi  maybe a simple solution would be to have an option so that when a job is completed, its jobId is updated, maybe with a counter that is specific for that jobId. By doing so you could still be able to avoid duplicates and at the same time add the same job after completion.

**Comment by manast** [comment]
@lxcid debounce in my view would imply that you put a job at the end of the queue, or delay it a bit. As soon as the job starts to process I do not think it is wise to tamper it.

**Comment by lxcid** [comment]
@manast thanks! noted. so messing with the internal state of a job (especially when it started, even within its own processor) is not recommend I guess.

my debouncing is more of on every time I add the same delayed job to the queue, it get delay further. For example, if I have an job that maybe send email in 15 min time, every time, I add the job, it reset the timer to 15 min again. The only issue is that behavior for debouncing when the the job already started can be vague.

If we can control the job's own state within its own processor, kinda like `job.progress()` but for like forcing it to retry or delay e.g.

```js
// NOTE: This is a proposal
queue.process('SEND_EMAIL', async (job) => {
  if (shouldSendNow) {
    return job.retry(60000); // retry in 1 minute time
  }
  // ... continue processing
});
```

I think we'll have more power to control these job destiny without worrying about re-queuing…

(I know my request is deviating from the main topic, should I file as a separate ticket for discussion?)

**Comment by manast** [comment]
@lxcid yes, this should be filled as an enhancement. For instance the ability to re-queue a job inside its process function. Currently when a job starts processing, the outcome can only be ```completed``` or ```failed```.
