### ISSUE TITLE
queue is ignoring priority if job has delay option too.

### ISSUE THREAD

**Issue by assafdd** [OptimalBits/bull#881]
## Description
Priority queues are working great. 
But if I add delay option to job, priority value seems to get ignored.

## Test code to reproduce
```js
const Queue = require('bull');
var priorityQueue = new Queue('priorityQueue', 'redis://127.0.0.1:6379');

priorityQueue.process(function(job){
    console.log(`processing job ${job.id} priority: ${job.data.p}`);
    return Promise.resolve();
});

priorityQueue.add({p: 2}, {priority:2 ,delay:10});
priorityQueue.add({p: 1}, {priority:1 ,delay:10});
```

## Bull version
3.3.9

**Comment by manast** [comment]
This is actually a design flaw in bull. Currently the priority is only used when adding a job to the queue, not in any other case when a job goes back to the wait state, this is true for delay, but also to retries in the case of failure, etc. Since it is not completely trivial to fix this, the question is how important is to support this case?

**Comment by assafdd** [comment]
Not too much. 
Yet, I think it's worth being documented.  I spent quite a lot of time trying to figure out why priorities are not working in my use case. 
If you feel fine with documenting this behaviour, I can send a PR on the REFERENCE.md#queueadd doc.
