### ISSUE TITLE
Huge slowdown in resolution of job.finished() promise if add called with some delay after process

### ISSUE THREAD

**Issue by pcernek-spare** [OptimalBits/bull#958]
## Description
Create a queue -> add a (trivial) processor function -> wait 100 ms -> add a job -> wait for `job.finished()`: takes ~5 seconds
Do the same thing, but remove the "wait 100 ms" step: takes ~ 200 ms

## Minimal, Working Test code to reproduce the issue.
*index.js*
```
const Queue = require('bull');
const Bluebird = require('bluebird')

const queue = new Queue('myTestQueue')
const delayMs = 100

queue.process((job) => {
  return job.data + 1
})
Bluebird.delay(delayMs).then(() => {
  queue.add(42).then((job) => {
    job.finished().then(process.exit)
  })
})
```

Run `time node index.js`: takes ~ 5 s
Set `delayMs` to 0 to remove the delay, run the same thing again: takes ~200 ms

## Bull version
3.4.2

## Additional information
Inserting some print statements suggests that the job gets processed very fast -- the bottleneck seems to be in the `job.finished()` promise resolving.

**Comment by manast** [comment]
thanks for the report. I know why this is happening, namely a side effect of the fact that setting a global event handler for the first time is an async function due its lazy nature. So we miss the completed event and it is handled by the watchdog. However this should only happen with the first bursts of jobs, after that the handler is setup and they will finalize much faster. I will take a look into some solution but I will lower the priority a bit since it is only affecting the initial queue status.
